package com.capp.springboot.util;

import java.io.BufferedReader;
import java.io.File;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;

import org.apache.commons.io.FileUtils;

import com.capp.springboot.object.SignInParams;

public class Test1 {
public static void main(String[] args) {
	/*
	 * File imagePath = new File(
	 * "D:\\SWorkspace\\ContactsAppSpringBoot\\src\\main\\webapp\\static_resources\\user_images\\CONTACTS_APP_98"
	 * ); try { FileUtils.deleteDirectory(imagePath); } catch (IOException e) { //
	 * TODO Auto-generated catch block e.printStackTrace(); }
	 */
	Test1 test = new Test1();
	//test.addColumn();
	//test.getColours();
	test.getUsers();
	//test.createUser();
	/*
	 * test.createCredsTable(); test.createColourTable(); test.createUser();
	 */
	test.getTables("public");
	test.insertIntoCities();
}
public void getTables(String schema) {
	Connection con = null;
	Statement stmt = null;
	ResultSet rs = null;
	try {
		con = DbUtil.getConnection("cloudPostgress");
		String selQuery = "SELECT * FROM information_schema.tables WHERE table_schema = '"+schema+"'";
		stmt = con.createStatement();
		rs = stmt.executeQuery(selQuery);
		while(rs.next()) {
			System.out.println(rs.getString("TABLE_NAME"));
		}
	} catch (Exception e) {
		try {
			DbUtil.closeResources(con, stmt, rs);
		} catch (DaoException e1) {
			// TODO Auto-generated catch block
			e1.printStackTrace();
		}
		System.out.println("Failed to create table");
		e.printStackTrace();
	}
}
public void addColumn() {
	Connection con = null;
	Statement stmt = null;
	ResultSet rs = null;
	try {
		con = DbUtil.getConnection("cloudPostgress");
		String altertable = "ALTER TABLE public.CONTACTS_APP_CREDS ADD COLUMN OTP varchar(250)";
		stmt = con.createStatement();
		stmt.executeUpdate(altertable);
		while(rs.next()) {
			System.out.println(rs.getString("USERNAME"));
			System.out.println(rs.getString("PASSWORD"));
			System.out.println(rs.getString("tablename"));
		}
	} catch (Exception e) {
		try {
			DbUtil.closeResources(con, stmt, rs);
		} catch (DaoException e1) {
			// TODO Auto-generated catch block
			e1.printStackTrace();
		}
		System.out.println("Failed to create table");
		e.printStackTrace();
	}
}

public void getUsers() {
	Connection con = null;
	Statement stmt = null;
	ResultSet rs = null;
	try {
		con = DbUtil.getConnection("cloudPostgress");
		String getUsers = "SELECT * FROM public.CONTACTS_APP_CREDS";// WHERE USERNAME='mgireesha73@gmail.com' AND OTP='48f5f23'";
		stmt = con.createStatement();
		rs = stmt.executeQuery(getUsers);
		while(rs.next()) {
			System.out.println(rs.getString("NAME")+", "+rs.getString("USERNAME")+", "+rs.getString("PASSWORD")+", "+rs.getString("TABLENAME"));
		}
	} catch (Exception e) {
		try {
			DbUtil.closeResources(con, stmt, rs);
		} catch (DaoException e1) {
			// TODO Auto-generated catch block
			e1.printStackTrace();
		}
		System.out.println("Failed to create table");
		e.printStackTrace();
	}
}

public void getColours() {
	Connection con = null;
	Statement stmt = null;
	ResultSet rs = null;
	try {
		con = DbUtil.getConnection("cloudPostgress");
		String getUsers = "SELECT * FROM public.CONTACTS_APP_COLOURS";// WHERE USERNAME='mgireesha73@gmail.com' AND OTP='48f5f23'";
		stmt = con.createStatement();
		rs = stmt.executeQuery(getUsers);
		while(rs.next()) {
			System.out.println(rs.getString("IDENTIFIER")+", "+rs.getString("NAVBAR")+", "+rs.getString("HEADERTEXT"));
		}
	} catch (Exception e) {
		try {
			DbUtil.closeResources(con, stmt, rs);
		} catch (DaoException e1) {
			// TODO Auto-generated catch block
			e1.printStackTrace();
		}
		System.out.println("Failed to create table");
		e.printStackTrace();
	}
}

public void createCredsTable() {
	Connection con = null;
	Statement stmt = null;
	try {
		con = DbUtil.getConnection("cloudPostgress");
		if(null!=con)
			System.out.println("Suucessfully connected to postgres");
		else
			System.out.println("Connection failed");
		String createCredsTable = "CREATE TABLE CONTACTS_APP_CREDS"
				+ "(USERNAME VARCHAR(250),PASSWORD VARCHAR(250),TABLENAME VARCHAR(250)"
				+ ",NAME VARCHAR(250),PHONE VARCHAR(250),GENDER VARCHAR(250),ID VARCHAR(250)"
				+ ",VIEW VARCHAR(250))";
		stmt = con.createStatement();
		stmt.executeUpdate(createCredsTable);
		System.out.println("Table CONTACT_APP_CREDS created successfully");
	} catch (Exception e) {
		System.out.println("Failed to create table");
		e.printStackTrace();
	}
}

public void createColourTable() {
	Connection con = null;
	Statement stmt = null;
	try {
		con = DbUtil.getConnection("cloudPostgress");
		if(null!=con)
			System.out.println("Suucessfully connected to postgres");
		else
			System.out.println("Connection failed");
		String createColursTable = "CREATE TABLE CONTACTS_APP_COLOURS"
				+ "(IDENTIFIER VARCHAR(200),NAVBAR VARCHAR(200),"
				+ "HEADERTEXT VARCHAR(200))";
		stmt = con.createStatement();
		stmt.executeUpdate(createColursTable);
		System.out.println("Table CONTACTS_APP_COLOURS created successfully");
	} catch (Exception e) {
		System.out.println("Failed to create table");
		e.printStackTrace();
	}
}

public String createUser() {
	String status = "";
	int statInt = 0 ;
	Connection con = null;
	PreparedStatement ps = null;
	Statement stmt = null;
	String usertable = null;
	int id = 0;
	CApUtil cUtil = new CApUtil();
	SignInParams userObj = new SignInParams();
	userObj.setEmail("mgireesha73@gmail.com");
	userObj.setPassWordFromDb("a");
	userObj.setNameFromDb("Gireesh MT");
	userObj.setPhone("9876543210");
	userObj.setGender("Male");
	String saveUser = "INSERT INTO public.CONTACTS_APP_CREDS (username, password, tableName,name, phone, gender, id, view) VALUES (?, ?, ?, ?, ?, ?, ?, ?)";
	String saveToColour = "INSERT INTO public.CONTACTS_APP_COLOURS (IDENTIFIER,NAVBAR,HEADERTEXT) VALUES (?,?,?)";
	try {
		con = DbUtil.getConnection("cloudPostgress");
		String maxId = cUtil.getMaXContactid(con, "public.CONTACTS_APP_CREDS");
		id = Integer.parseInt(maxId);
		usertable = "CONTACTS_APP_"+id;
		ps = con.prepareStatement(saveUser);
		ps.setString(1, userObj.getEmail());
		ps.setString(2, userObj.getPassWordFromDb());
		ps.setString(3, usertable);
		ps.setString(4, userObj.getNameFromDb());
		ps.setString(5, userObj.getPhone());
		ps.setString(6, userObj.getGender());
		ps.setInt(7, id);
		ps.setString(8, "basic");
		//statInt = ps.executeUpdate();
		statInt=1;
		if(statInt==1) {
			ps = con.prepareStatement(saveToColour); 
			ps.setString(1, usertable);
			ps.setString(2, "");
			ps.setString(3, "");
			//statInt = ps.executeUpdate();
			if(statInt == 1) {
				usertable="CONTACTS_APP_100004";
				String createTable="CREATE TABLE "+usertable+" (NAME VARCHAR(200),GENDER VARCHAR(20),EMAIL VARCHAR(200),PHONE VARCHAR(200),CITY VARCHAR(200),ADDRESS VARCHAR(200),STATE VARCHAR(200),ID VARCHAR(200),DP bytea)";
				stmt = con.createStatement();
				stmt.executeUpdate(createTable);
				status = "Success";
			}
		}
	} catch (DaoException e) {
		e.printStackTrace();
	} catch (SQLException e) {
		e.printStackTrace();
	}finally {
		try {
			DbUtil.closeResources(con, stmt,ps);
		} catch (DaoException e) {
			e.printStackTrace();
		}
	}
	return status;
}

public void createStatesTable() {
	Connection con = null;
	Statement stmt = null;
	try {
		con = DbUtil.getConnection("cloudPostgress");
		if(null!=con)
			System.out.println("Suucessfully connected to postgres");
		else
			System.out.println("Connection failed");
		String createColursTable = "CREATE TABLE PUBLIC.STATES(ID INTEGER NOT NULL,NAME VARCHAR(50) NOT NULL,COUNTRY_ID INTEGER NOT NULL)";
		stmt = con.createStatement();
		stmt.executeUpdate(createColursTable);
		System.out.println("Table CONTACTS_APP_COLOURS created successfully");
	} catch (Exception e) {
		System.out.println("Failed to create table");
		e.printStackTrace();
	}
}

public List<String> getQueries(){
	Path pathToFile = Paths.get("");
	List<String> list = new ArrayList<String>();
	String line = null;
	try(BufferedReader br = Files.newBufferedReader(pathToFile,StandardCharsets.US_ASCII)){
		line = br.readLine();
		if(null!=line)
			list.add(line);
		
	}catch (Exception e) {
		// TODO: handle exception
	}
	return list;
}

public void insertIntoCities() {
	Connection con = null;
	Statement stmt = null;
	try {
		con = DbUtil.getConnection("cloudPostgress");
		if(null!=con)
			System.out.println("Suucessfully connected to postgres");
		else
			System.out.println("Connection failed");
		String createColursTable = "INSERT INTO cities (city_id, city_name, city_state) VALUES\r\n"
				+ "(1, 'Kolhapur', 'Maharashtra'),\r\n"
				+ "(2, 'Port Blair', 'Andaman and Nicobar Islands'),\r\n"
				+ "(3, 'Adilabad', 'Andhra Pradesh'),\r\n"
				+ "(4, 'Adoni', 'Andhra Pradesh'),\r\n"
				+ "(5, 'Amadalavalasa', 'Andhra Pradesh'),\r\n"
				+ "(6, 'Amalapuram', 'Andhra Pradesh'),\r\n"
				+ "(7, 'Anakapalle', 'Andhra Pradesh'),\r\n"
				+ "(8, 'Anantapur', 'Andhra Pradesh'),\r\n"
				+ "(9, 'Badepalle', 'Andhra Pradesh'),\r\n"
				+ "(10, 'Banganapalle', 'Andhra Pradesh'),\r\n"
				+ "(11, 'Bapatla', 'Andhra Pradesh'),\r\n"
				+ "(12, 'Bellampalle', 'Andhra Pradesh'),\r\n"
				+ "(13, 'Bethamcherla', 'Andhra Pradesh'),\r\n"
				+ "(14, 'Bhadrachalam', 'Andhra Pradesh'),\r\n"
				+ "(15, 'Bhainsa', 'Andhra Pradesh'),\r\n"
				+ "(16, 'Bheemunipatnam', 'Andhra Pradesh'),\r\n"
				+ "(17, 'Bhimavaram', 'Andhra Pradesh'),\r\n"
				+ "(18, 'Bhongir', 'Andhra Pradesh'),\r\n"
				+ "(19, 'Bobbili', 'Andhra Pradesh'),\r\n"
				+ "(20, 'Bodhan', 'Andhra Pradesh'),\r\n"
				+ "(21, 'Chilakaluripet', 'Andhra Pradesh'),\r\n"
				+ "(22, 'Chirala', 'Andhra Pradesh'),\r\n"
				+ "(23, 'Chittoor', 'Andhra Pradesh'),\r\n"
				+ "(24, 'Cuddapah', 'Andhra Pradesh'),\r\n"
				+ "(25, 'Devarakonda', 'Andhra Pradesh'),\r\n"
				+ "(26, 'Dharmavaram', 'Andhra Pradesh'),\r\n"
				+ "(27, 'Eluru', 'Andhra Pradesh'),\r\n"
				+ "(28, 'Farooqnagar', 'Andhra Pradesh'),\r\n"
				+ "(29, 'Gadwal', 'Andhra Pradesh'),\r\n"
				+ "(30, 'Gooty', 'Andhra Pradesh'),\r\n"
				+ "(31, 'Gudivada', 'Andhra Pradesh'),\r\n"
				+ "(32, 'Gudur', 'Andhra Pradesh'),\r\n"
				+ "(33, 'Guntakal', 'Andhra Pradesh'),\r\n"
				+ "(34, 'Guntur', 'Andhra Pradesh'),\r\n"
				+ "(35, 'Hanuman Junction', 'Andhra Pradesh'),\r\n"
				+ "(36, 'Hindupur', 'Andhra Pradesh'),\r\n"
				+ "(37, 'Hyderabad', 'Andhra Pradesh'),\r\n"
				+ "(38, 'Ichchapuram', 'Andhra Pradesh'),\r\n"
				+ "(39, 'Jaggaiahpet', 'Andhra Pradesh'),\r\n"
				+ "(40, 'Jagtial', 'Andhra Pradesh'),\r\n"
				+ "(41, 'Jammalamadugu', 'Andhra Pradesh'),\r\n"
				+ "(42, 'Jangaon', 'Andhra Pradesh'),\r\n"
				+ "(43, 'Kadapa', 'Andhra Pradesh'),\r\n"
				+ "(44, 'Kadiri', 'Andhra Pradesh'),\r\n"
				+ "(45, 'Kagaznagar', 'Andhra Pradesh'),\r\n"
				+ "(46, 'Kakinada', 'Andhra Pradesh'),\r\n"
				+ "(47, 'Kalyandurg', 'Andhra Pradesh'),\r\n"
				+ "(48, 'Kamareddy', 'Andhra Pradesh'),\r\n"
				+ "(49, 'Kandukur', 'Andhra Pradesh'),\r\n"
				+ "(50, 'Karimnagar', 'Andhra Pradesh'),\r\n"
				+ "(51, 'Kavali', 'Andhra Pradesh'),\r\n"
				+ "(52, 'Khammam', 'Andhra Pradesh'),\r\n"
				+ "(53, 'Koratla', 'Andhra Pradesh'),\r\n"
				+ "(54, 'Kothagudem', 'Andhra Pradesh'),\r\n"
				+ "(55, 'Kothapeta', 'Andhra Pradesh'),\r\n"
				+ "(56, 'Kovvur', 'Andhra Pradesh'),\r\n"
				+ "(57, 'Kurnool', 'Andhra Pradesh'),\r\n"
				+ "(58, 'Kyathampalle', 'Andhra Pradesh'),\r\n"
				+ "(59, 'Macherla', 'Andhra Pradesh'),\r\n"
				+ "(60, 'Machilipatnam', 'Andhra Pradesh'),\r\n"
				+ "(61, 'Madanapalle', 'Andhra Pradesh'),\r\n"
				+ "(62, 'Mahbubnagar', 'Andhra Pradesh'),\r\n"
				+ "(63, 'Mancherial', 'Andhra Pradesh'),\r\n"
				+ "(64, 'Mandamarri', 'Andhra Pradesh'),\r\n"
				+ "(65, 'Mandapeta', 'Andhra Pradesh'),\r\n"
				+ "(66, 'Manuguru', 'Andhra Pradesh'),\r\n"
				+ "(67, 'Markapur', 'Andhra Pradesh'),\r\n"
				+ "(68, 'Medak', 'Andhra Pradesh'),\r\n"
				+ "(69, 'Miryalaguda', 'Andhra Pradesh'),\r\n"
				+ "(70, 'Mogalthur', 'Andhra Pradesh'),\r\n"
				+ "(71, 'Nagari', 'Andhra Pradesh'),\r\n"
				+ "(72, 'Nagarkurnool', 'Andhra Pradesh'),\r\n"
				+ "(73, 'Nandyal', 'Andhra Pradesh'),\r\n"
				+ "(74, 'Narasapur', 'Andhra Pradesh'),\r\n"
				+ "(75, 'Narasaraopet', 'Andhra Pradesh'),\r\n"
				+ "(76, 'Narayanpet', 'Andhra Pradesh'),\r\n"
				+ "(77, 'Narsipatnam', 'Andhra Pradesh'),\r\n"
				+ "(78, 'Nellore', 'Andhra Pradesh'),\r\n"
				+ "(79, 'Nidadavole', 'Andhra Pradesh'),\r\n"
				+ "(80, 'Nirmal', 'Andhra Pradesh'),\r\n"
				+ "(81, 'Nizamabad', 'Andhra Pradesh'),\r\n"
				+ "(82, 'Nuzvid', 'Andhra Pradesh'),\r\n"
				+ "(83, 'Ongole', 'Andhra Pradesh'),\r\n"
				+ "(84, 'Palacole', 'Andhra Pradesh'),\r\n"
				+ "(85, 'Palasa Kasibugga', 'Andhra Pradesh'),\r\n"
				+ "(86, 'Palwancha', 'Andhra Pradesh'),\r\n"
				+ "(87, 'Parvathipuram', 'Andhra Pradesh'),\r\n"
				+ "(88, 'Pedana', 'Andhra Pradesh'),\r\n"
				+ "(89, 'Peddapuram', 'Andhra Pradesh'),\r\n"
				+ "(90, 'Pithapuram', 'Andhra Pradesh'),\r\n"
				+ "(91, 'Pondur', 'Andhra pradesh'),\r\n"
				+ "(92, 'Ponnur', 'Andhra Pradesh'),\r\n"
				+ "(93, 'Proddatur', 'Andhra Pradesh'),\r\n"
				+ "(94, 'Punganur', 'Andhra Pradesh'),\r\n"
				+ "(95, 'Puttur', 'Andhra Pradesh'),\r\n"
				+ "(96, 'Rajahmundry', 'Andhra Pradesh'),\r\n"
				+ "(97, 'Rajam', 'Andhra Pradesh'),\r\n"
				+ "(98, 'Ramachandrapuram', 'Andhra Pradesh'),\r\n"
				+ "(99, 'Ramagundam', 'Andhra Pradesh'),\r\n"
				+ "(100, 'Rayachoti', 'Andhra Pradesh'),\r\n"
				+ "(101, 'Rayadurg', 'Andhra Pradesh'),\r\n"
				+ "(102, 'Renigunta', 'Andhra Pradesh'),\r\n"
				+ "(103, 'Repalle', 'Andhra Pradesh'),\r\n"
				+ "(104, 'Sadasivpet', 'Andhra Pradesh'),\r\n"
				+ "(105, 'Salur', 'Andhra Pradesh'),\r\n"
				+ "(106, 'Samalkot', 'Andhra Pradesh'),\r\n"
				+ "(107, 'Sangareddy', 'Andhra Pradesh'),\r\n"
				+ "(108, 'Sattenapalle', 'Andhra Pradesh'),\r\n"
				+ "(109, 'Siddipet', 'Andhra Pradesh'),\r\n"
				+ "(110, 'Singapur', 'Andhra Pradesh'),\r\n"
				+ "(111, 'Sircilla', 'Andhra Pradesh'),\r\n"
				+ "(112, 'Srikakulam', 'Andhra Pradesh'),\r\n"
				+ "(113, 'Srikalahasti', 'Andhra Pradesh'),\r\n"
				+ "(115, 'Suryapet', 'Andhra Pradesh'),\r\n"
				+ "(116, 'Tadepalligudem', 'Andhra Pradesh'),\r\n"
				+ "(117, 'Tadpatri', 'Andhra Pradesh'),\r\n"
				+ "(118, 'Tandur', 'Andhra Pradesh'),\r\n"
				+ "(119, 'Tanuku', 'Andhra Pradesh'),\r\n"
				+ "(120, 'Tenali', 'Andhra Pradesh'),\r\n"
				+ "(121, 'Tirupati', 'Andhra Pradesh'),\r\n"
				+ "(122, 'Tuni', 'Andhra Pradesh'),\r\n"
				+ "(123, 'Uravakonda', 'Andhra Pradesh'),\r\n"
				+ "(124, 'Venkatagiri', 'Andhra Pradesh'),\r\n"
				+ "(125, 'Vicarabad', 'Andhra Pradesh'),\r\n"
				+ "(126, 'Vijayawada', 'Andhra Pradesh'),\r\n"
				+ "(127, 'Vinukonda', 'Andhra Pradesh'),\r\n"
				+ "(128, 'Visakhapatnam', 'Andhra Pradesh'),\r\n"
				+ "(129, 'Vizianagaram', 'Andhra Pradesh'),\r\n"
				+ "(130, 'Wanaparthy', 'Andhra Pradesh'),\r\n"
				+ "(131, 'Warangal', 'Andhra Pradesh'),\r\n"
				+ "(132, 'Yellandu', 'Andhra Pradesh'),\r\n"
				+ "(133, 'Yemmiganur', 'Andhra Pradesh'),\r\n"
				+ "(134, 'Yerraguntla', 'Andhra Pradesh'),\r\n"
				+ "(135, 'Zahirabad', 'Andhra Pradesh'),\r\n"
				+ "(136, 'Rajampet', 'Andra Pradesh'),\r\n"
				+ "(137, 'Along', 'Arunachal Pradesh'),\r\n"
				+ "(138, 'Bomdila', 'Arunachal Pradesh'),\r\n"
				+ "(139, 'Itanagar', 'Arunachal Pradesh'),\r\n"
				+ "(140, 'Naharlagun', 'Arunachal Pradesh'),\r\n"
				+ "(141, 'Pasighat', 'Arunachal Pradesh'),\r\n"
				+ "(142, 'Abhayapuri', 'Assam'),\r\n"
				+ "(143, 'Amguri', 'Assam'),\r\n"
				+ "(144, 'Anandnagaar', 'Assam'),\r\n"
				+ "(145, 'Barpeta', 'Assam'),\r\n"
				+ "(146, 'Barpeta Road', 'Assam'),\r\n"
				+ "(147, 'Bilasipara', 'Assam'),\r\n"
				+ "(148, 'Bongaigaon', 'Assam'),\r\n"
				+ "(149, 'Dhekiajuli', 'Assam'),\r\n"
				+ "(150, 'Dhubri', 'Assam'),\r\n"
				+ "(151, 'Dibrugarh', 'Assam'),\r\n"
				+ "(152, 'Digboi', 'Assam'),\r\n"
				+ "(153, 'Diphu', 'Assam'),\r\n"
				+ "(154, 'Dispur', 'Assam'),\r\n"
				+ "(156, 'Gauripur', 'Assam'),\r\n"
				+ "(157, 'Goalpara', 'Assam'),\r\n"
				+ "(158, 'Golaghat', 'Assam'),\r\n"
				+ "(159, 'Guwahati', 'Assam'),\r\n"
				+ "(160, 'Haflong', 'Assam'),\r\n"
				+ "(161, 'Hailakandi', 'Assam'),\r\n"
				+ "(162, 'Hojai', 'Assam'),\r\n"
				+ "(163, 'Jorhat', 'Assam'),\r\n"
				+ "(164, 'Karimganj', 'Assam'),\r\n"
				+ "(165, 'Kokrajhar', 'Assam'),\r\n"
				+ "(166, 'Lanka', 'Assam'),\r\n"
				+ "(167, 'Lumding', 'Assam'),\r\n"
				+ "(168, 'Mangaldoi', 'Assam'),\r\n"
				+ "(169, 'Mankachar', 'Assam'),\r\n"
				+ "(170, 'Margherita', 'Assam'),\r\n"
				+ "(171, 'Mariani', 'Assam'),\r\n"
				+ "(172, 'Marigaon', 'Assam'),\r\n"
				+ "(173, 'Nagaon', 'Assam'),\r\n"
				+ "(174, 'Nalbari', 'Assam'),\r\n"
				+ "(175, 'North Lakhimpur', 'Assam'),\r\n"
				+ "(176, 'Rangia', 'Assam'),\r\n"
				+ "(177, 'Sibsagar', 'Assam'),\r\n"
				+ "(178, 'Silapathar', 'Assam'),\r\n"
				+ "(179, 'Silchar', 'Assam'),\r\n"
				+ "(180, 'Tezpur', 'Assam'),\r\n"
				+ "(181, 'Tinsukia', 'Assam'),\r\n"
				+ "(182, 'Amarpur', 'Bihar'),\r\n"
				+ "(183, 'Araria', 'Bihar'),\r\n"
				+ "(184, 'Areraj', 'Bihar'),\r\n"
				+ "(185, 'Arrah', 'Bihar'),\r\n"
				+ "(186, 'Asarganj', 'Bihar'),\r\n"
				+ "(187, 'Aurangabad', 'Bihar'),\r\n"
				+ "(188, 'Bagaha', 'Bihar'),\r\n"
				+ "(189, 'Bahadurganj', 'Bihar'),\r\n"
				+ "(190, 'Bairgania', 'Bihar'),\r\n"
				+ "(191, 'Bakhtiarpur', 'Bihar'),\r\n"
				+ "(192, 'Banka', 'Bihar'),\r\n"
				+ "(193, 'Banmankhi Bazar', 'Bihar'),\r\n"
				+ "(194, 'Barahiya', 'Bihar'),\r\n"
				+ "(195, 'Barauli', 'Bihar'),\r\n"
				+ "(196, 'Barbigha', 'Bihar'),\r\n"
				+ "(197, 'Barh', 'Bihar'),\r\n"
				+ "(198, 'Begusarai', 'Bihar'),\r\n"
				+ "(199, 'Behea', 'Bihar'),\r\n"
				+ "(200, 'Bettiah', 'Bihar'),\r\n"
				+ "(201, 'Bhabua', 'Bihar'),\r\n"
				+ "(202, 'Bhagalpur', 'Bihar'),\r\n"
				+ "(203, 'Bihar Sharif', 'Bihar'),\r\n"
				+ "(204, 'Bikramganj', 'Bihar'),\r\n"
				+ "(205, 'Bodh Gaya', 'Bihar'),\r\n"
				+ "(206, 'Buxar', 'Bihar'),\r\n"
				+ "(207, 'Chandan Bara', 'Bihar'),\r\n"
				+ "(208, 'Chanpatia', 'Bihar'),\r\n"
				+ "(209, 'Chhapra', 'Bihar'),\r\n"
				+ "(210, 'Colgong', 'Bihar'),\r\n"
				+ "(211, 'Dalsinghsarai', 'Bihar'),\r\n"
				+ "(212, 'Darbhanga', 'Bihar'),\r\n"
				+ "(213, 'Daudnagar', 'Bihar'),\r\n"
				+ "(214, 'Dehri-on-Sone', 'Bihar'),\r\n"
				+ "(215, 'Dhaka', 'Bihar'),\r\n"
				+ "(216, 'Dighwara', 'Bihar'),\r\n"
				+ "(217, 'Dumraon', 'Bihar'),\r\n"
				+ "(218, 'Fatwah', 'Bihar'),\r\n"
				+ "(219, 'Forbesganj', 'Bihar'),\r\n"
				+ "(220, 'Gaya', 'Bihar'),\r\n"
				+ "(221, 'Gogri Jamalpur', 'Bihar'),\r\n"
				+ "(222, 'Gopalganj', 'Bihar'),\r\n"
				+ "(223, 'Hajipur', 'Bihar'),\r\n"
				+ "(224, 'Hilsa', 'Bihar'),\r\n"
				+ "(225, 'Hisua', 'Bihar'),\r\n"
				+ "(226, 'Islampur', 'Bihar'),\r\n"
				+ "(227, 'Jagdispur', 'Bihar'),\r\n"
				+ "(228, 'Jamalpur', 'Bihar'),\r\n"
				+ "(229, 'Jamui', 'Bihar'),\r\n"
				+ "(230, 'Jehanabad', 'Bihar'),\r\n"
				+ "(231, 'Jhajha', 'Bihar'),\r\n"
				+ "(232, 'Jhanjharpur', 'Bihar'),\r\n"
				+ "(233, 'Jogabani', 'Bihar'),\r\n"
				+ "(234, 'Kanti', 'Bihar'),\r\n"
				+ "(235, 'Katihar', 'Bihar'),\r\n"
				+ "(236, 'Khagaria', 'Bihar'),\r\n"
				+ "(237, 'Kharagpur', 'Bihar'),\r\n"
				+ "(238, 'Kishanganj', 'Bihar'),\r\n"
				+ "(239, 'Lakhisarai', 'Bihar'),\r\n"
				+ "(240, 'Lalganj', 'Bihar'),\r\n"
				+ "(241, 'Madhepura', 'Bihar'),\r\n"
				+ "(242, 'Madhubani', 'Bihar'),\r\n"
				+ "(243, 'Maharajganj', 'Bihar'),\r\n"
				+ "(244, 'Mahnar Bazar', 'Bihar'),\r\n"
				+ "(245, 'Makhdumpur', 'Bihar'),\r\n"
				+ "(246, 'Maner', 'Bihar'),\r\n"
				+ "(247, 'Manihari', 'Bihar'),\r\n"
				+ "(248, 'Marhaura', 'Bihar'),\r\n"
				+ "(249, 'Masaurhi', 'Bihar'),\r\n"
				+ "(250, 'Mirganj', 'Bihar'),\r\n"
				+ "(251, 'Mokameh', 'Bihar'),\r\n"
				+ "(252, 'Motihari', 'Bihar'),\r\n"
				+ "(253, 'Motipur', 'Bihar'),\r\n"
				+ "(254, 'Munger', 'Bihar'),\r\n"
				+ "(255, 'Murliganj', 'Bihar'),\r\n"
				+ "(256, 'Muzaffarpur', 'Bihar'),\r\n"
				+ "(257, 'Narkatiaganj', 'Bihar'),\r\n"
				+ "(258, 'Naugachhia', 'Bihar'),\r\n"
				+ "(259, 'Nawada', 'Bihar'),\r\n"
				+ "(260, 'Nokha', 'Bihar'),\r\n"
				+ "(261, 'Patna', 'Bihar'),\r\n"
				+ "(262, 'Piro', 'Bihar'),\r\n"
				+ "(263, 'Purnia', 'Bihar'),\r\n"
				+ "(264, 'Rafiganj', 'Bihar'),\r\n"
				+ "(265, 'Rajgir', 'Bihar'),\r\n"
				+ "(266, 'Ramnagar', 'Bihar'),\r\n"
				+ "(267, 'Raxaul Bazar', 'Bihar'),\r\n"
				+ "(268, 'Revelganj', 'Bihar'),\r\n"
				+ "(269, 'Rosera', 'Bihar'),\r\n"
				+ "(270, 'Saharsa', 'Bihar'),\r\n"
				+ "(271, 'Samastipur', 'Bihar'),\r\n"
				+ "(272, 'Sasaram', 'Bihar'),\r\n"
				+ "(273, 'Sheikhpura', 'Bihar'),\r\n"
				+ "(274, 'Sheohar', 'Bihar'),\r\n"
				+ "(275, 'Sherghati', 'Bihar'),\r\n"
				+ "(276, 'Silao', 'Bihar'),\r\n"
				+ "(277, 'Sitamarhi', 'Bihar'),\r\n"
				+ "(278, 'Siwan', 'Bihar'),\r\n"
				+ "(279, 'Sonepur', 'Bihar'),\r\n"
				+ "(280, 'Sugauli', 'Bihar'),\r\n"
				+ "(281, 'Sultanganj', 'Bihar'),\r\n"
				+ "(282, 'Supaul', 'Bihar'),\r\n"
				+ "(283, 'Warisaliganj', 'Bihar'),\r\n"
				+ "(284, 'Ahiwara', 'Chhattisgarh'),\r\n"
				+ "(285, 'Akaltara', 'Chhattisgarh'),\r\n"
				+ "(286, 'Ambagarh Chowki', 'Chhattisgarh'),\r\n"
				+ "(287, 'Ambikapur', 'Chhattisgarh'),\r\n"
				+ "(288, 'Arang', 'Chhattisgarh'),\r\n"
				+ "(289, 'Bade Bacheli', 'Chhattisgarh'),\r\n"
				+ "(290, 'Balod', 'Chhattisgarh'),\r\n"
				+ "(291, 'Baloda Bazar', 'Chhattisgarh'),\r\n"
				+ "(292, 'Bemetra', 'Chhattisgarh'),\r\n"
				+ "(293, 'Bhatapara', 'Chhattisgarh'),\r\n"
				+ "(294, 'Bilaspur', 'Chhattisgarh'),\r\n"
				+ "(295, 'Birgaon', 'Chhattisgarh'),\r\n"
				+ "(296, 'Champa', 'Chhattisgarh'),\r\n"
				+ "(297, 'Chirmiri', 'Chhattisgarh'),\r\n"
				+ "(298, 'Dalli-Rajhara', 'Chhattisgarh'),\r\n"
				+ "(299, 'Dhamtari', 'Chhattisgarh'),\r\n"
				+ "(300, 'Dipka', 'Chhattisgarh'),\r\n"
				+ "(301, 'Dongargarh', 'Chhattisgarh'),\r\n"
				+ "(302, 'Durg-Bhilai Nagar', 'Chhattisgarh'),\r\n"
				+ "(303, 'Gobranawapara', 'Chhattisgarh'),\r\n"
				+ "(304, 'Jagdalpur', 'Chhattisgarh'),\r\n"
				+ "(305, 'Janjgir', 'Chhattisgarh'),\r\n"
				+ "(306, 'Jashpurnagar', 'Chhattisgarh'),\r\n"
				+ "(307, 'Kanker', 'Chhattisgarh'),\r\n"
				+ "(308, 'Kawardha', 'Chhattisgarh'),\r\n"
				+ "(309, 'Kondagaon', 'Chhattisgarh'),\r\n"
				+ "(310, 'Korba', 'Chhattisgarh'),\r\n"
				+ "(311, 'Mahasamund', 'Chhattisgarh'),\r\n"
				+ "(312, 'Mahendragarh', 'Chhattisgarh'),\r\n"
				+ "(313, 'Mungeli', 'Chhattisgarh'),\r\n"
				+ "(314, 'Naila Janjgir', 'Chhattisgarh'),\r\n"
				+ "(315, 'Raigarh', 'Chhattisgarh'),\r\n"
				+ "(316, 'Raipur', 'Chhattisgarh'),\r\n"
				+ "(317, 'Rajnandgaon', 'Chhattisgarh'),\r\n"
				+ "(318, 'Sakti', 'Chhattisgarh'),\r\n"
				+ "(319, 'Tilda Newra', 'Chhattisgarh'),\r\n"
				+ "(320, 'Amli', 'Dadra & Nagar Haveli'),\r\n"
				+ "(321, 'Silvassa', 'Dadra and Nagar Haveli'),\r\n"
				+ "(322, 'Daman and Diu', 'Daman & Diu'),\r\n"
				+ "(323, 'Daman and Diu', 'Daman & Diu'),\r\n"
				+ "(324, 'Asola', 'Delhi'),\r\n"
				+ "(325, 'Delhi', 'Delhi'),\r\n"
				+ "(326, 'Aldona', 'Goa'),\r\n"
				+ "(327, 'Curchorem Cacora', 'Goa'),\r\n"
				+ "(328, 'Madgaon', 'Goa'),\r\n"
				+ "(329, 'Mapusa', 'Goa'),\r\n"
				+ "(330, 'Margao', 'Goa'),\r\n"
				+ "(331, 'Marmagao', 'Goa'),\r\n"
				+ "(332, 'Panaji', 'Goa'),\r\n"
				+ "(333, 'Ahmedabad', 'Gujarat'),\r\n"
				+ "(334, 'Amreli', 'Gujarat'),\r\n"
				+ "(335, 'Anand', 'Gujarat'),\r\n"
				+ "(336, 'Ankleshwar', 'Gujarat'),\r\n"
				+ "(337, 'Bharuch', 'Gujarat'),\r\n"
				+ "(338, 'Bhavnagar', 'Gujarat'),\r\n"
				+ "(339, 'Bhuj', 'Gujarat'),\r\n"
				+ "(340, 'Cambay', 'Gujarat'),\r\n"
				+ "(341, 'Dahod', 'Gujarat'),\r\n"
				+ "(342, 'Deesa', 'Gujarat'),\r\n"
				+ "(343, '\"Dharampur', ' India\"'),\r\n"
				+ "(344, 'Dholka', 'Gujarat'),\r\n"
				+ "(345, 'Gandhinagar', 'Gujarat'),\r\n"
				+ "(346, 'Godhra', 'Gujarat'),\r\n"
				+ "(347, 'Himatnagar', 'Gujarat'),\r\n"
				+ "(348, 'Idar', 'Gujarat'),\r\n"
				+ "(349, 'Jamnagar', 'Gujarat'),\r\n"
				+ "(350, 'Junagadh', 'Gujarat'),\r\n"
				+ "(351, 'Kadi', 'Gujarat'),\r\n"
				+ "(352, 'Kalavad', 'Gujarat'),\r\n"
				+ "(353, 'Kalol', 'Gujarat'),\r\n"
				+ "(354, 'Kapadvanj', 'Gujarat'),\r\n"
				+ "(355, 'Karjan', 'Gujarat'),\r\n"
				+ "(356, 'Keshod', 'Gujarat'),\r\n"
				+ "(357, 'Khambhalia', 'Gujarat'),\r\n"
				+ "(358, 'Khambhat', 'Gujarat'),\r\n"
				+ "(359, 'Kheda', 'Gujarat'),\r\n"
				+ "(360, 'Khedbrahma', 'Gujarat'),\r\n"
				+ "(361, 'Kheralu', 'Gujarat'),\r\n"
				+ "(362, 'Kodinar', 'Gujarat'),\r\n"
				+ "(363, 'Lathi', 'Gujarat'),\r\n"
				+ "(364, 'Limbdi', 'Gujarat'),\r\n"
				+ "(365, 'Lunawada', 'Gujarat'),\r\n"
				+ "(366, 'Mahesana', 'Gujarat'),\r\n"
				+ "(367, 'Mahuva', 'Gujarat'),\r\n"
				+ "(368, 'Manavadar', 'Gujarat'),\r\n"
				+ "(369, 'Mandvi', 'Gujarat'),\r\n"
				+ "(370, 'Mangrol', 'Gujarat'),\r\n"
				+ "(371, 'Mansa', 'Gujarat'),\r\n"
				+ "(372, 'Mehmedabad', 'Gujarat'),\r\n"
				+ "(373, 'Modasa', 'Gujarat'),\r\n"
				+ "(374, 'Morvi', 'Gujarat'),\r\n"
				+ "(375, 'Nadiad', 'Gujarat'),\r\n"
				+ "(376, 'Navsari', 'Gujarat'),\r\n"
				+ "(377, 'Padra', 'Gujarat'),\r\n"
				+ "(378, 'Palanpur', 'Gujarat'),\r\n"
				+ "(379, 'Palitana', 'Gujarat'),\r\n"
				+ "(380, 'Pardi', 'Gujarat'),\r\n"
				+ "(381, 'Patan', 'Gujarat'),\r\n"
				+ "(382, 'Petlad', 'Gujarat'),\r\n"
				+ "(383, 'Porbandar', 'Gujarat'),\r\n"
				+ "(384, 'Radhanpur', 'Gujarat'),\r\n"
				+ "(385, 'Rajkot', 'Gujarat'),\r\n"
				+ "(386, 'Rajpipla', 'Gujarat'),\r\n"
				+ "(387, 'Rajula', 'Gujarat'),\r\n"
				+ "(388, 'Ranavav', 'Gujarat'),\r\n"
				+ "(389, 'Rapar', 'Gujarat'),\r\n"
				+ "(390, 'Salaya', 'Gujarat'),\r\n"
				+ "(391, 'Sanand', 'Gujarat'),\r\n"
				+ "(392, 'Savarkundla', 'Gujarat'),\r\n"
				+ "(393, 'Sidhpur', 'Gujarat'),\r\n"
				+ "(394, 'Sihor', 'Gujarat'),\r\n"
				+ "(395, 'Songadh', 'Gujarat'),\r\n"
				+ "(396, 'Surat', 'Gujarat'),\r\n"
				+ "(397, 'Talaja', 'Gujarat'),\r\n"
				+ "(398, 'Thangadh', 'Gujarat'),\r\n"
				+ "(399, 'Tharad', 'Gujarat'),\r\n"
				+ "(400, 'Umbergaon', 'Gujarat'),\r\n"
				+ "(401, 'Umreth', 'Gujarat'),\r\n"
				+ "(402, 'Una', 'Gujarat'),\r\n"
				+ "(403, 'Unjha', 'Gujarat'),\r\n"
				+ "(404, 'Upleta', 'Gujarat'),\r\n"
				+ "(405, 'Vadnagar', 'Gujarat'),\r\n"
				+ "(406, 'Vadodara', 'Gujarat'),\r\n"
				+ "(407, 'Valsad', 'Gujarat'),\r\n"
				+ "(408, 'Vapi', 'Gujarat'),\r\n"
				+ "(409, 'Vapi', 'Gujarat'),\r\n"
				+ "(410, 'Veraval', 'Gujarat'),\r\n"
				+ "(411, 'Vijapur', 'Gujarat'),\r\n"
				+ "(412, 'Viramgam', 'Gujarat'),\r\n"
				+ "(413, 'Visnagar', 'Gujarat'),\r\n"
				+ "(414, 'Vyara', 'Gujarat'),\r\n"
				+ "(415, 'Wadhwan', 'Gujarat'),\r\n"
				+ "(416, 'Wankaner', 'Gujarat'),\r\n"
				+ "(417, 'Adalaj', 'Gujrat'),\r\n"
				+ "(418, 'Adityana', 'Gujrat'),\r\n"
				+ "(419, 'Alang', 'Gujrat'),\r\n"
				+ "(420, 'Ambaji', 'Gujrat'),\r\n"
				+ "(421, 'Ambaliyasan', 'Gujrat'),\r\n"
				+ "(422, 'Andada', 'Gujrat'),\r\n"
				+ "(423, 'Anjar', 'Gujrat'),\r\n"
				+ "(424, 'Anklav', 'Gujrat'),\r\n"
				+ "(425, 'Antaliya', 'Gujrat'),\r\n"
				+ "(426, 'Arambhada', 'Gujrat'),\r\n"
				+ "(427, 'Atul', 'Gujrat'),\r\n"
				+ "(428, 'Ballabhgarh', 'Hariyana'),\r\n"
				+ "(429, 'Ambala', 'Haryana'),\r\n"
				+ "(430, 'Ambala', 'Haryana'),\r\n"
				+ "(431, 'Asankhurd', 'Haryana'),\r\n"
				+ "(432, 'Assandh', 'Haryana'),\r\n"
				+ "(433, 'Ateli', 'Haryana'),\r\n"
				+ "(434, 'Babiyal', 'Haryana'),\r\n"
				+ "(435, 'Bahadurgarh', 'Haryana'),\r\n"
				+ "(436, 'Barwala', 'Haryana'),\r\n"
				+ "(437, 'Bhiwani', 'Haryana'),\r\n"
				+ "(438, 'Charkhi Dadri', 'Haryana'),\r\n"
				+ "(439, 'Cheeka', 'Haryana'),\r\n"
				+ "(440, 'Ellenabad 2', 'Haryana'),\r\n"
				+ "(441, 'Faridabad', 'Haryana'),\r\n"
				+ "(442, 'Fatehabad', 'Haryana'),\r\n"
				+ "(443, 'Ganaur', 'Haryana'),\r\n"
				+ "(444, 'Gharaunda', 'Haryana'),\r\n"
				+ "(445, 'Gohana', 'Haryana'),\r\n"
				+ "(446, 'Gurgaon', 'Haryana'),\r\n"
				+ "(447, 'Haibat(Yamuna Nagar)', 'Haryana'),\r\n"
				+ "(448, 'Hansi', 'Haryana'),\r\n"
				+ "(449, 'Hisar', 'Haryana'),\r\n"
				+ "(450, 'Hodal', 'Haryana'),\r\n"
				+ "(451, 'Jhajjar', 'Haryana'),\r\n"
				+ "(452, 'Jind', 'Haryana'),\r\n"
				+ "(453, 'Kaithal', 'Haryana'),\r\n"
				+ "(454, 'Kalan Wali', 'Haryana'),\r\n"
				+ "(455, 'Kalka', 'Haryana'),\r\n"
				+ "(456, 'Karnal', 'Haryana'),\r\n"
				+ "(457, 'Ladwa', 'Haryana'),\r\n"
				+ "(458, 'Mahendragarh', 'Haryana'),\r\n"
				+ "(459, 'Mandi Dabwali', 'Haryana'),\r\n"
				+ "(460, 'Narnaul', 'Haryana'),\r\n"
				+ "(461, 'Narwana', 'Haryana'),\r\n"
				+ "(462, 'Palwal', 'Haryana'),\r\n"
				+ "(463, 'Panchkula', 'Haryana'),\r\n"
				+ "(464, 'Panipat', 'Haryana'),\r\n"
				+ "(465, 'Pehowa', 'Haryana'),\r\n"
				+ "(466, 'Pinjore', 'Haryana'),\r\n"
				+ "(467, 'Rania', 'Haryana'),\r\n"
				+ "(468, 'Ratia', 'Haryana'),\r\n"
				+ "(469, 'Rewari', 'Haryana'),\r\n"
				+ "(470, 'Rohtak', 'Haryana'),\r\n"
				+ "(471, 'Safidon', 'Haryana'),\r\n"
				+ "(472, 'Samalkha', 'Haryana'),\r\n"
				+ "(473, 'Shahbad', 'Haryana'),\r\n"
				+ "(474, 'Sirsa', 'Haryana'),\r\n"
				+ "(475, 'Sohna', 'Haryana'),\r\n"
				+ "(476, 'Sonipat', 'Haryana'),\r\n"
				+ "(477, 'Taraori', 'Haryana'),\r\n"
				+ "(478, 'Thanesar', 'Haryana'),\r\n"
				+ "(479, 'Tohana', 'Haryana'),\r\n"
				+ "(480, 'Yamunanagar', 'Haryana'),\r\n"
				+ "(481, 'Arki', 'Himachal Pradesh'),\r\n"
				+ "(482, 'Baddi', 'Himachal Pradesh'),\r\n"
				+ "(483, 'Bilaspur', 'Himachal Pradesh'),\r\n"
				+ "(484, 'Chamba', 'Himachal Pradesh'),\r\n"
				+ "(485, 'Dalhousie', 'Himachal Pradesh'),\r\n"
				+ "(486, 'Dharamsala', 'Himachal Pradesh'),\r\n"
				+ "(487, 'Hamirpur', 'Himachal Pradesh'),\r\n"
				+ "(488, 'Mandi', 'Himachal Pradesh'),\r\n"
				+ "(489, 'Nahan', 'Himachal Pradesh'),\r\n"
				+ "(490, 'Shimla', 'Himachal Pradesh'),\r\n"
				+ "(491, 'Solan', 'Himachal Pradesh'),\r\n"
				+ "(492, 'Sundarnagar', 'Himachal Pradesh'),\r\n"
				+ "(493, 'Jammu', 'Jammu & Kashmir'),\r\n"
				+ "(494, 'Achabbal', 'Jammu and Kashmir'),\r\n"
				+ "(495, 'Akhnoor', 'Jammu and Kashmir'),\r\n"
				+ "(496, 'Anantnag', 'Jammu and Kashmir'),\r\n"
				+ "(497, 'Arnia', 'Jammu and Kashmir'),\r\n"
				+ "(498, 'Awantipora', 'Jammu and Kashmir'),\r\n"
				+ "(499, 'Bandipore', 'Jammu and Kashmir'),\r\n"
				+ "(500, 'Baramula', 'Jammu and Kashmir'),\r\n"
				+ "(501, 'Kathua', 'Jammu and Kashmir'),\r\n"
				+ "(502, 'Leh', 'Jammu and Kashmir'),\r\n"
				+ "(503, 'Punch', 'Jammu and Kashmir'),\r\n"
				+ "(504, 'Rajauri', 'Jammu and Kashmir'),\r\n"
				+ "(505, 'Sopore', 'Jammu and Kashmir'),\r\n"
				+ "(506, 'Srinagar', 'Jammu and Kashmir'),\r\n"
				+ "(507, 'Udhampur', 'Jammu and Kashmir'),\r\n"
				+ "(508, 'Amlabad', 'Jharkhand'),\r\n"
				+ "(509, 'Ara', 'Jharkhand'),\r\n"
				+ "(510, 'Barughutu', 'Jharkhand'),\r\n"
				+ "(511, 'Bokaro Steel City', 'Jharkhand'),\r\n"
				+ "(512, 'Chaibasa', 'Jharkhand'),\r\n"
				+ "(513, 'Chakradharpur', 'Jharkhand'),\r\n"
				+ "(514, 'Chandrapura', 'Jharkhand'),\r\n"
				+ "(515, 'Chatra', 'Jharkhand'),\r\n"
				+ "(516, 'Chirkunda', 'Jharkhand'),\r\n"
				+ "(517, 'Churi', 'Jharkhand'),\r\n"
				+ "(518, 'Daltonganj', 'Jharkhand'),\r\n"
				+ "(519, 'Deoghar', 'Jharkhand'),\r\n"
				+ "(520, 'Dhanbad', 'Jharkhand'),\r\n"
				+ "(521, 'Dumka', 'Jharkhand'),\r\n"
				+ "(522, 'Garhwa', 'Jharkhand'),\r\n"
				+ "(523, 'Ghatshila', 'Jharkhand'),\r\n"
				+ "(524, 'Giridih', 'Jharkhand'),\r\n"
				+ "(525, 'Godda', 'Jharkhand'),\r\n"
				+ "(526, 'Gomoh', 'Jharkhand'),\r\n"
				+ "(527, 'Gumia', 'Jharkhand'),\r\n"
				+ "(528, 'Gumla', 'Jharkhand'),\r\n"
				+ "(529, 'Hazaribag', 'Jharkhand'),\r\n"
				+ "(530, 'Hussainabad', 'Jharkhand'),\r\n"
				+ "(531, 'Jamshedpur', 'Jharkhand'),\r\n"
				+ "(532, 'Jamtara', 'Jharkhand'),\r\n"
				+ "(533, 'Jhumri Tilaiya', 'Jharkhand'),\r\n"
				+ "(534, 'Khunti', 'Jharkhand'),\r\n"
				+ "(535, 'Lohardaga', 'Jharkhand'),\r\n"
				+ "(536, 'Madhupur', 'Jharkhand'),\r\n"
				+ "(537, 'Mihijam', 'Jharkhand'),\r\n"
				+ "(538, 'Musabani', 'Jharkhand'),\r\n"
				+ "(539, 'Pakaur', 'Jharkhand'),\r\n"
				+ "(540, 'Patratu', 'Jharkhand'),\r\n"
				+ "(541, 'Phusro', 'Jharkhand'),\r\n"
				+ "(542, 'Ramngarh', 'Jharkhand'),\r\n"
				+ "(543, 'Ranchi', 'Jharkhand'),\r\n"
				+ "(544, 'Sahibganj', 'Jharkhand'),\r\n"
				+ "(545, 'Saunda', 'Jharkhand'),\r\n"
				+ "(546, 'Simdega', 'Jharkhand'),\r\n"
				+ "(547, 'Tenu Dam-cum- Kathhara', 'Jharkhand'),\r\n"
				+ "(548, 'Arasikere', 'Karnataka'),\r\n"
				+ "(549, 'Bangalore', 'Karnataka'),\r\n"
				+ "(550, 'Belgaum', 'Karnataka'),\r\n"
				+ "(551, 'Bellary', 'Karnataka'),\r\n"
				+ "(552, 'Chamrajnagar', 'Karnataka'),\r\n"
				+ "(553, 'Chikkaballapur', 'Karnataka'),\r\n"
				+ "(554, 'Chintamani', 'Karnataka'),\r\n"
				+ "(555, 'Chitradurga', 'Karnataka'),\r\n"
				+ "(556, 'Gulbarga', 'Karnataka'),\r\n"
				+ "(557, 'Gundlupet', 'Karnataka'),\r\n"
				+ "(558, 'Hassan', 'Karnataka'),\r\n"
				+ "(559, 'Hospet', 'Karnataka'),\r\n"
				+ "(560, 'Hubli', 'Karnataka'),\r\n"
				+ "(561, 'Karkala', 'Karnataka'),\r\n"
				+ "(562, 'Karwar', 'Karnataka'),\r\n"
				+ "(563, 'Kolar', 'Karnataka'),\r\n"
				+ "(564, 'Kota', 'Karnataka'),\r\n"
				+ "(565, 'Lakshmeshwar', 'Karnataka'),\r\n"
				+ "(566, 'Lingsugur', 'Karnataka'),\r\n"
				+ "(567, 'Maddur', 'Karnataka'),\r\n"
				+ "(568, 'Madhugiri', 'Karnataka'),\r\n"
				+ "(569, 'Madikeri', 'Karnataka'),\r\n"
				+ "(570, 'Magadi', 'Karnataka'),\r\n"
				+ "(571, 'Mahalingpur', 'Karnataka'),\r\n"
				+ "(572, 'Malavalli', 'Karnataka'),\r\n"
				+ "(573, 'Malur', 'Karnataka'),\r\n"
				+ "(574, 'Mandya', 'Karnataka'),\r\n"
				+ "(575, 'Mangalore', 'Karnataka'),\r\n"
				+ "(576, 'Manvi', 'Karnataka'),\r\n"
				+ "(577, 'Mudalgi', 'Karnataka'),\r\n"
				+ "(578, 'Mudbidri', 'Karnataka'),\r\n"
				+ "(579, 'Muddebihal', 'Karnataka'),\r\n"
				+ "(580, 'Mudhol', 'Karnataka'),\r\n"
				+ "(581, 'Mulbagal', 'Karnataka'),\r\n"
				+ "(582, 'Mundargi', 'Karnataka'),\r\n"
				+ "(583, 'Mysore', 'Karnataka'),\r\n"
				+ "(584, 'Nanjangud', 'Karnataka'),\r\n"
				+ "(585, 'Pavagada', 'Karnataka'),\r\n"
				+ "(586, 'Puttur', 'Karnataka'),\r\n"
				+ "(587, 'Rabkavi Banhatti', 'Karnataka'),\r\n"
				+ "(588, 'Raichur', 'Karnataka'),\r\n"
				+ "(589, 'Ramanagaram', 'Karnataka'),\r\n"
				+ "(590, 'Ramdurg', 'Karnataka'),\r\n"
				+ "(591, 'Ranibennur', 'Karnataka'),\r\n"
				+ "(592, 'Robertson Pet', 'Karnataka'),\r\n"
				+ "(593, 'Ron', 'Karnataka'),\r\n"
				+ "(594, 'Sadalgi', 'Karnataka'),\r\n"
				+ "(595, 'Sagar', 'Karnataka'),\r\n"
				+ "(596, 'Sakleshpur', 'Karnataka'),\r\n"
				+ "(597, 'Sandur', 'Karnataka'),\r\n"
				+ "(598, 'Sankeshwar', 'Karnataka'),\r\n"
				+ "(599, 'Saundatti-Yellamma', 'Karnataka'),\r\n"
				+ "(600, 'Savanur', 'Karnataka'),\r\n"
				+ "(601, 'Sedam', 'Karnataka'),\r\n"
				+ "(602, 'Shahabad', 'Karnataka'),\r\n"
				+ "(603, 'Shahpur', 'Karnataka'),\r\n"
				+ "(604, 'Shiggaon', 'Karnataka'),\r\n"
				+ "(605, 'Shikapur', 'Karnataka'),\r\n"
				+ "(606, 'Shimoga', 'Karnataka'),\r\n"
				+ "(607, 'Shorapur', 'Karnataka'),\r\n"
				+ "(608, 'Shrirangapattana', 'Karnataka'),\r\n"
				+ "(609, 'Sidlaghatta', 'Karnataka'),\r\n"
				+ "(610, 'Sindgi', 'Karnataka'),\r\n"
				+ "(611, 'Sindhnur', 'Karnataka'),\r\n"
				+ "(612, 'Sira', 'Karnataka'),\r\n"
				+ "(613, 'Sirsi', 'Karnataka'),\r\n"
				+ "(614, 'Siruguppa', 'Karnataka'),\r\n"
				+ "(615, 'Srinivaspur', 'Karnataka'),\r\n"
				+ "(616, 'Talikota', 'Karnataka'),\r\n"
				+ "(617, 'Tarikere', 'Karnataka'),\r\n"
				+ "(618, 'Tekkalakota', 'Karnataka'),\r\n"
				+ "(619, 'Terdal', 'Karnataka'),\r\n"
				+ "(620, 'Tiptur', 'Karnataka'),\r\n"
				+ "(621, 'Tumkur', 'Karnataka'),\r\n"
				+ "(622, 'Udupi', 'Karnataka'),\r\n"
				+ "(623, 'Vijayapura', 'Karnataka'),\r\n"
				+ "(624, 'Wadi', 'Karnataka'),\r\n"
				+ "(625, 'Yadgir', 'Karnataka'),\r\n"
				+ "(626, 'Adoor', 'Kerala'),\r\n"
				+ "(627, 'Akathiyoor', 'Kerala'),\r\n"
				+ "(628, 'Alappuzha', 'Kerala'),\r\n"
				+ "(629, 'Ancharakandy', 'Kerala'),\r\n"
				+ "(630, 'Aroor', 'Kerala'),\r\n"
				+ "(631, 'Ashtamichira', 'Kerala'),\r\n"
				+ "(632, 'Attingal', 'Kerala'),\r\n"
				+ "(633, 'Avinissery', 'Kerala'),\r\n"
				+ "(634, 'Chalakudy', 'Kerala'),\r\n"
				+ "(635, 'Changanassery', 'Kerala'),\r\n"
				+ "(636, 'Chendamangalam', 'Kerala'),\r\n"
				+ "(637, 'Chengannur', 'Kerala'),\r\n"
				+ "(638, 'Cherthala', 'Kerala'),\r\n"
				+ "(639, 'Cheruthazham', 'Kerala'),\r\n"
				+ "(640, 'Chittur-Thathamangalam', 'Kerala'),\r\n"
				+ "(641, 'Chockli', 'Kerala'),\r\n"
				+ "(642, 'Erattupetta', 'Kerala'),\r\n"
				+ "(643, 'Guruvayoor', 'Kerala'),\r\n"
				+ "(644, 'Irinjalakuda', 'Kerala'),\r\n"
				+ "(645, 'Kadirur', 'Kerala'),\r\n"
				+ "(646, 'Kalliasseri', 'Kerala'),\r\n"
				+ "(647, 'Kalpetta', 'Kerala'),\r\n"
				+ "(648, 'Kanhangad', 'Kerala'),\r\n"
				+ "(649, 'Kanjikkuzhi', 'Kerala'),\r\n"
				+ "(650, 'Kannur', 'Kerala'),\r\n"
				+ "(651, 'Kasaragod', 'Kerala'),\r\n"
				+ "(652, 'Kayamkulam', 'Kerala'),\r\n"
				+ "(653, 'Kochi', 'Kerala'),\r\n"
				+ "(654, 'Kodungallur', 'Kerala'),\r\n"
				+ "(655, 'Kollam', 'Kerala'),\r\n"
				+ "(656, 'Koothuparamba', 'Kerala'),\r\n"
				+ "(657, 'Kothamangalam', 'Kerala'),\r\n"
				+ "(658, 'Kottayam', 'Kerala'),\r\n"
				+ "(659, 'Kozhikode', 'Kerala'),\r\n"
				+ "(660, 'Kunnamkulam', 'Kerala'),\r\n"
				+ "(661, 'Malappuram', 'Kerala'),\r\n"
				+ "(662, 'Mattannur', 'Kerala'),\r\n"
				+ "(663, 'Mavelikkara', 'Kerala'),\r\n"
				+ "(664, 'Mavoor', 'Kerala'),\r\n"
				+ "(665, 'Muvattupuzha', 'Kerala'),\r\n"
				+ "(666, 'Nedumangad', 'Kerala'),\r\n"
				+ "(667, 'Neyyattinkara', 'Kerala'),\r\n"
				+ "(668, 'Ottappalam', 'Kerala'),\r\n"
				+ "(669, 'Palai', 'Kerala'),\r\n"
				+ "(670, 'Palakkad', 'Kerala'),\r\n"
				+ "(671, 'Panniyannur', 'Kerala'),\r\n"
				+ "(672, 'Pappinisseri', 'Kerala'),\r\n"
				+ "(673, 'Paravoor', 'Kerala'),\r\n"
				+ "(674, 'Pathanamthitta', 'Kerala'),\r\n"
				+ "(675, 'Payyannur', 'Kerala'),\r\n"
				+ "(676, 'Peringathur', 'Kerala'),\r\n"
				+ "(677, 'Perinthalmanna', 'Kerala'),\r\n"
				+ "(678, 'Perumbavoor', 'Kerala'),\r\n"
				+ "(679, 'Ponnani', 'Kerala'),\r\n"
				+ "(680, 'Punalur', 'Kerala'),\r\n"
				+ "(681, 'Quilandy', 'Kerala'),\r\n"
				+ "(682, 'Shoranur', 'Kerala'),\r\n"
				+ "(683, 'Taliparamba', 'Kerala'),\r\n"
				+ "(684, 'Thiruvalla', 'Kerala'),\r\n"
				+ "(685, 'Thiruvananthapuram', 'Kerala'),\r\n"
				+ "(686, 'Thodupuzha', 'Kerala'),\r\n"
				+ "(687, 'Thrissur', 'Kerala'),\r\n"
				+ "(688, 'Tirur', 'Kerala'),\r\n"
				+ "(689, 'Vadakara', 'Kerala'),\r\n"
				+ "(690, 'Vaikom', 'Kerala'),\r\n"
				+ "(691, 'Varkala', 'Kerala'),\r\n"
				+ "(692, 'Kavaratti', 'Lakshadweep'),\r\n"
				+ "(693, 'Ashok Nagar', 'Madhya Pradesh'),\r\n"
				+ "(694, 'Balaghat', 'Madhya Pradesh'),\r\n"
				+ "(695, 'Betul', 'Madhya Pradesh'),\r\n"
				+ "(696, 'Bhopal', 'Madhya Pradesh'),\r\n"
				+ "(697, 'Burhanpur', 'Madhya Pradesh'),\r\n"
				+ "(698, 'Chhatarpur', 'Madhya Pradesh'),\r\n"
				+ "(699, 'Dabra', 'Madhya Pradesh'),\r\n"
				+ "(700, 'Datia', 'Madhya Pradesh'),\r\n"
				+ "(701, 'Dewas', 'Madhya Pradesh'),\r\n"
				+ "(702, 'Dhar', 'Madhya Pradesh'),\r\n"
				+ "(703, 'Fatehabad', 'Madhya Pradesh'),\r\n"
				+ "(704, 'Gwalior', 'Madhya Pradesh'),\r\n"
				+ "(705, 'Indore', 'Madhya Pradesh'),\r\n"
				+ "(706, 'Itarsi', 'Madhya Pradesh'),\r\n"
				+ "(707, 'Jabalpur', 'Madhya Pradesh'),\r\n"
				+ "(708, 'Katni', 'Madhya Pradesh'),\r\n"
				+ "(709, 'Kotma', 'Madhya Pradesh'),\r\n"
				+ "(710, 'Lahar', 'Madhya Pradesh'),\r\n"
				+ "(711, 'Lundi', 'Madhya Pradesh'),\r\n"
				+ "(712, 'Maharajpur', 'Madhya Pradesh'),\r\n"
				+ "(713, 'Mahidpur', 'Madhya Pradesh'),\r\n"
				+ "(714, 'Maihar', 'Madhya Pradesh'),\r\n"
				+ "(715, 'Malajkhand', 'Madhya Pradesh'),\r\n"
				+ "(716, 'Manasa', 'Madhya Pradesh'),\r\n"
				+ "(717, 'Manawar', 'Madhya Pradesh'),\r\n"
				+ "(718, 'Mandideep', 'Madhya Pradesh'),\r\n"
				+ "(719, 'Mandla', 'Madhya Pradesh'),\r\n"
				+ "(720, 'Mandsaur', 'Madhya Pradesh'),\r\n"
				+ "(721, 'Mauganj', 'Madhya Pradesh'),\r\n"
				+ "(722, 'Mhow Cantonment', 'Madhya Pradesh'),\r\n"
				+ "(723, 'Mhowgaon', 'Madhya Pradesh'),\r\n"
				+ "(724, 'Morena', 'Madhya Pradesh'),\r\n"
				+ "(725, 'Multai', 'Madhya Pradesh'),\r\n"
				+ "(726, 'Murwara', 'Madhya Pradesh'),\r\n"
				+ "(727, 'Nagda', 'Madhya Pradesh'),\r\n"
				+ "(728, 'Nainpur', 'Madhya Pradesh'),\r\n"
				+ "(729, 'Narsinghgarh', 'Madhya Pradesh'),\r\n"
				+ "(730, 'Narsinghgarh', 'Madhya Pradesh'),\r\n"
				+ "(731, 'Neemuch', 'Madhya Pradesh'),\r\n"
				+ "(732, 'Nepanagar', 'Madhya Pradesh'),\r\n"
				+ "(733, 'Niwari', 'Madhya Pradesh'),\r\n"
				+ "(734, 'Nowgong', 'Madhya Pradesh'),\r\n"
				+ "(735, 'Nowrozabad', 'Madhya Pradesh'),\r\n"
				+ "(736, 'Pachore', 'Madhya Pradesh'),\r\n"
				+ "(737, 'Pali', 'Madhya Pradesh'),\r\n"
				+ "(738, 'Panagar', 'Madhya Pradesh'),\r\n"
				+ "(739, 'Pandhurna', 'Madhya Pradesh'),\r\n"
				+ "(740, 'Panna', 'Madhya Pradesh'),\r\n"
				+ "(741, 'Pasan', 'Madhya Pradesh'),\r\n"
				+ "(742, 'Pipariya', 'Madhya Pradesh'),\r\n"
				+ "(743, 'Pithampur', 'Madhya Pradesh'),\r\n"
				+ "(744, 'Porsa', 'Madhya Pradesh'),\r\n"
				+ "(745, 'Prithvipur', 'Madhya Pradesh'),\r\n"
				+ "(746, 'Raghogarh-Vijaypur', 'Madhya Pradesh'),\r\n"
				+ "(747, 'Rahatgarh', 'Madhya Pradesh'),\r\n"
				+ "(748, 'Raisen', 'Madhya Pradesh'),\r\n"
				+ "(749, 'Rajgarh', 'Madhya Pradesh'),\r\n"
				+ "(750, 'Ratlam', 'Madhya Pradesh'),\r\n"
				+ "(751, 'Rau', 'Madhya Pradesh'),\r\n"
				+ "(752, 'Rehli', 'Madhya Pradesh'),\r\n"
				+ "(753, 'Rewa', 'Madhya Pradesh'),\r\n"
				+ "(754, 'Sabalgarh', 'Madhya Pradesh'),\r\n"
				+ "(755, 'Sagar', 'Madhya Pradesh'),\r\n"
				+ "(756, 'Sanawad', 'Madhya Pradesh'),\r\n"
				+ "(757, 'Sarangpur', 'Madhya Pradesh'),\r\n"
				+ "(758, 'Sarni', 'Madhya Pradesh'),\r\n"
				+ "(759, 'Satna', 'Madhya Pradesh'),\r\n"
				+ "(760, 'Sausar', 'Madhya Pradesh'),\r\n"
				+ "(761, 'Sehore', 'Madhya Pradesh'),\r\n"
				+ "(762, 'Sendhwa', 'Madhya Pradesh'),\r\n"
				+ "(763, 'Seoni', 'Madhya Pradesh'),\r\n"
				+ "(764, 'Seoni-Malwa', 'Madhya Pradesh'),\r\n"
				+ "(765, 'Shahdol', 'Madhya Pradesh'),\r\n"
				+ "(766, 'Shajapur', 'Madhya Pradesh'),\r\n"
				+ "(767, 'Shamgarh', 'Madhya Pradesh'),\r\n"
				+ "(768, 'Sheopur', 'Madhya Pradesh'),\r\n"
				+ "(769, 'Shivpuri', 'Madhya Pradesh'),\r\n"
				+ "(770, 'Shujalpur', 'Madhya Pradesh'),\r\n"
				+ "(771, 'Sidhi', 'Madhya Pradesh'),\r\n"
				+ "(772, 'Sihora', 'Madhya Pradesh'),\r\n"
				+ "(773, 'Singrauli', 'Madhya Pradesh'),\r\n"
				+ "(774, 'Sironj', 'Madhya Pradesh'),\r\n"
				+ "(775, 'Sohagpur', 'Madhya Pradesh'),\r\n"
				+ "(776, 'Tarana', 'Madhya Pradesh'),\r\n"
				+ "(777, 'Tikamgarh', 'Madhya Pradesh'),\r\n"
				+ "(778, 'Ujhani', 'Madhya Pradesh'),\r\n"
				+ "(779, 'Ujjain', 'Madhya Pradesh'),\r\n"
				+ "(780, 'Umaria', 'Madhya Pradesh'),\r\n"
				+ "(781, 'Vidisha', 'Madhya Pradesh'),\r\n"
				+ "(782, 'Wara Seoni', 'Madhya Pradesh'),\r\n"
				+ "(783, 'Ahmednagar', 'Maharashtra'),\r\n"
				+ "(784, 'Akola', 'Maharashtra'),\r\n"
				+ "(785, 'Amravati', 'Maharashtra'),\r\n"
				+ "(786, 'Aurangabad', 'Maharashtra'),\r\n"
				+ "(787, 'Baramati', 'Maharashtra'),\r\n"
				+ "(788, 'Chalisgaon', 'Maharashtra'),\r\n"
				+ "(789, 'Chinchani', 'Maharashtra'),\r\n"
				+ "(790, 'Devgarh', 'Maharashtra'),\r\n"
				+ "(791, 'Dhule', 'Maharashtra'),\r\n"
				+ "(792, 'Dombivli', 'Maharashtra'),\r\n"
				+ "(793, 'Durgapur', 'Maharashtra'),\r\n"
				+ "(794, 'Ichalkaranji', 'Maharashtra'),\r\n"
				+ "(795, 'Jalna', 'Maharashtra'),\r\n"
				+ "(796, 'Kalyan', 'Maharashtra'),\r\n"
				+ "(797, 'Latur', 'Maharashtra'),\r\n"
				+ "(798, 'Loha', 'Maharashtra'),\r\n"
				+ "(799, 'Lonar', 'Maharashtra'),\r\n"
				+ "(800, 'Lonavla', 'Maharashtra'),\r\n"
				+ "(801, 'Mahad', 'Maharashtra'),\r\n"
				+ "(802, 'Mahuli', 'Maharashtra'),\r\n"
				+ "(803, 'Malegaon', 'Maharashtra'),\r\n"
				+ "(804, 'Malkapur', 'Maharashtra'),\r\n"
				+ "(805, 'Manchar', 'Maharashtra'),\r\n"
				+ "(806, 'Mangalvedhe', 'Maharashtra'),\r\n"
				+ "(807, 'Mangrulpir', 'Maharashtra'),\r\n"
				+ "(808, 'Manjlegaon', 'Maharashtra'),\r\n"
				+ "(809, 'Manmad', 'Maharashtra'),\r\n"
				+ "(810, 'Manwath', 'Maharashtra'),\r\n"
				+ "(811, 'Mehkar', 'Maharashtra'),\r\n"
				+ "(812, 'Mhaswad', 'Maharashtra'),\r\n"
				+ "(813, 'Miraj', 'Maharashtra'),\r\n"
				+ "(814, 'Morshi', 'Maharashtra'),\r\n"
				+ "(815, 'Mukhed', 'Maharashtra'),\r\n"
				+ "(816, 'Mul', 'Maharashtra'),\r\n"
				+ "(817, 'Mumbai', 'Maharashtra'),\r\n"
				+ "(818, 'Murtijapur', 'Maharashtra'),\r\n"
				+ "(819, 'Nagpur', 'Maharashtra'),\r\n"
				+ "(820, 'Nalasopara', 'Maharashtra'),\r\n"
				+ "(821, 'Nanded-Waghala', 'Maharashtra'),\r\n"
				+ "(822, 'Nandgaon', 'Maharashtra'),\r\n"
				+ "(823, 'Nandura', 'Maharashtra'),\r\n"
				+ "(824, 'Nandurbar', 'Maharashtra'),\r\n"
				+ "(825, 'Narkhed', 'Maharashtra'),\r\n"
				+ "(826, 'Nashik', 'Maharashtra'),\r\n"
				+ "(827, 'Navi Mumbai', 'Maharashtra'),\r\n"
				+ "(828, 'Nawapur', 'Maharashtra'),\r\n"
				+ "(829, 'Nilanga', 'Maharashtra'),\r\n"
				+ "(830, 'Osmanabad', 'Maharashtra'),\r\n"
				+ "(831, 'Ozar', 'Maharashtra'),\r\n"
				+ "(832, 'Pachora', 'Maharashtra'),\r\n"
				+ "(833, 'Paithan', 'Maharashtra'),\r\n"
				+ "(834, 'Palghar', 'Maharashtra'),\r\n"
				+ "(835, 'Pandharkaoda', 'Maharashtra'),\r\n"
				+ "(836, 'Pandharpur', 'Maharashtra'),\r\n"
				+ "(837, 'Panvel', 'Maharashtra'),\r\n"
				+ "(838, 'Parbhani', 'Maharashtra'),\r\n"
				+ "(839, 'Parli', 'Maharashtra'),\r\n"
				+ "(840, 'Parola', 'Maharashtra'),\r\n"
				+ "(841, 'Partur', 'Maharashtra'),\r\n"
				+ "(842, 'Pathardi', 'Maharashtra'),\r\n"
				+ "(843, 'Pathri', 'Maharashtra'),\r\n"
				+ "(844, 'Patur', 'Maharashtra'),\r\n"
				+ "(845, 'Pauni', 'Maharashtra'),\r\n"
				+ "(846, 'Pen', 'Maharashtra'),\r\n"
				+ "(847, 'Phaltan', 'Maharashtra'),\r\n"
				+ "(848, 'Pulgaon', 'Maharashtra'),\r\n"
				+ "(849, 'Pune', 'Maharashtra'),\r\n"
				+ "(850, 'Purna', 'Maharashtra'),\r\n"
				+ "(851, 'Pusad', 'Maharashtra'),\r\n"
				+ "(852, 'Rahuri', 'Maharashtra'),\r\n"
				+ "(853, 'Rajura', 'Maharashtra'),\r\n"
				+ "(854, 'Ramtek', 'Maharashtra'),\r\n"
				+ "(855, 'Ratnagiri', 'Maharashtra'),\r\n"
				+ "(856, 'Raver', 'Maharashtra'),\r\n"
				+ "(857, 'Risod', 'Maharashtra'),\r\n"
				+ "(858, 'Sailu', 'Maharashtra'),\r\n"
				+ "(859, 'Sangamner', 'Maharashtra'),\r\n"
				+ "(860, 'Sangli', 'Maharashtra'),\r\n"
				+ "(861, 'Sangole', 'Maharashtra'),\r\n"
				+ "(862, 'Sasvad', 'Maharashtra'),\r\n"
				+ "(863, 'Satana', 'Maharashtra'),\r\n"
				+ "(864, 'Satara', 'Maharashtra'),\r\n"
				+ "(865, 'Savner', 'Maharashtra'),\r\n"
				+ "(866, 'Sawantwadi', 'Maharashtra'),\r\n"
				+ "(867, 'Shahade', 'Maharashtra'),\r\n"
				+ "(868, 'Shegaon', 'Maharashtra'),\r\n"
				+ "(869, 'Shendurjana', 'Maharashtra'),\r\n"
				+ "(870, 'Shirdi', 'Maharashtra'),\r\n"
				+ "(871, 'Shirpur-Warwade', 'Maharashtra'),\r\n"
				+ "(872, 'Shirur', 'Maharashtra'),\r\n"
				+ "(873, 'Shrigonda', 'Maharashtra'),\r\n"
				+ "(874, 'Shrirampur', 'Maharashtra'),\r\n"
				+ "(875, 'Sillod', 'Maharashtra'),\r\n"
				+ "(876, 'Sinnar', 'Maharashtra'),\r\n"
				+ "(877, 'Solapur', 'Maharashtra'),\r\n"
				+ "(878, 'Soyagaon', 'Maharashtra'),\r\n"
				+ "(879, 'Talegaon Dabhade', 'Maharashtra'),\r\n"
				+ "(880, 'Talode', 'Maharashtra'),\r\n"
				+ "(881, 'Tasgaon', 'Maharashtra'),\r\n"
				+ "(882, 'Tirora', 'Maharashtra'),\r\n"
				+ "(883, 'Tuljapur', 'Maharashtra'),\r\n"
				+ "(884, 'Tumsar', 'Maharashtra'),\r\n"
				+ "(885, 'Uran', 'Maharashtra'),\r\n"
				+ "(886, 'Uran Islampur', 'Maharashtra'),\r\n"
				+ "(887, 'Wadgaon Road', 'Maharashtra'),\r\n"
				+ "(888, 'Wai', 'Maharashtra'),\r\n"
				+ "(889, 'Wani', 'Maharashtra'),\r\n"
				+ "(890, 'Wardha', 'Maharashtra'),\r\n"
				+ "(891, 'Warora', 'Maharashtra'),\r\n"
				+ "(892, 'Warud', 'Maharashtra'),\r\n"
				+ "(893, 'Washim', 'Maharashtra'),\r\n"
				+ "(894, 'Yevla', 'Maharashtra'),\r\n"
				+ "(895, 'Uchgaon', 'Maharastra'),\r\n"
				+ "(896, 'Udgir', 'Maharastra'),\r\n"
				+ "(897, 'Umarga', 'Maharastra'),\r\n"
				+ "(898, 'Umarkhed', 'Maharastra'),\r\n"
				+ "(899, 'Umred', 'Maharastra'),\r\n"
				+ "(900, 'Vadgaon Kasba', 'Maharastra'),\r\n"
				+ "(901, 'Vaijapur', 'Maharastra'),\r\n"
				+ "(902, 'Vasai', 'Maharastra'),\r\n"
				+ "(903, 'Virar', 'Maharastra'),\r\n"
				+ "(904, 'Vita', 'Maharastra'),\r\n"
				+ "(905, 'Yavatmal', 'Maharastra'),\r\n"
				+ "(906, 'Yawal', 'Maharastra'),\r\n"
				+ "(907, 'Imphal', 'Manipur'),\r\n"
				+ "(908, 'Kakching', 'Manipur'),\r\n"
				+ "(909, 'Lilong', 'Manipur'),\r\n"
				+ "(910, 'Mayang Imphal', 'Manipur'),\r\n"
				+ "(911, 'Thoubal', 'Manipur'),\r\n"
				+ "(912, 'Jowai', 'Meghalaya'),\r\n"
				+ "(913, 'Nongstoin', 'Meghalaya'),\r\n"
				+ "(914, 'Shillong', 'Meghalaya'),\r\n"
				+ "(915, 'Tura', 'Meghalaya'),\r\n"
				+ "(916, 'Aizawl', 'Mizoram'),\r\n"
				+ "(917, 'Champhai', 'Mizoram'),\r\n"
				+ "(918, 'Lunglei', 'Mizoram'),\r\n"
				+ "(919, 'Saiha', 'Mizoram'),\r\n"
				+ "(920, 'Dimapur', 'Nagaland'),\r\n"
				+ "(921, 'Kohima', 'Nagaland'),\r\n"
				+ "(922, 'Mokokchung', 'Nagaland'),\r\n"
				+ "(923, 'Tuensang', 'Nagaland'),\r\n"
				+ "(924, 'Wokha', 'Nagaland'),\r\n"
				+ "(925, 'Zunheboto', 'Nagaland'),\r\n"
				+ "(950, 'Anandapur', 'Orissa'),\r\n"
				+ "(951, 'Anugul', 'Orissa'),\r\n"
				+ "(952, 'Asika', 'Orissa'),\r\n"
				+ "(953, 'Balangir', 'Orissa'),\r\n"
				+ "(954, 'Balasore', 'Orissa'),\r\n"
				+ "(955, 'Baleshwar', 'Orissa'),\r\n"
				+ "(956, 'Bamra', 'Orissa'),\r\n"
				+ "(957, 'Barbil', 'Orissa'),\r\n"
				+ "(958, 'Bargarh', 'Orissa'),\r\n"
				+ "(959, 'Bargarh', 'Orissa'),\r\n"
				+ "(960, 'Baripada', 'Orissa'),\r\n"
				+ "(961, 'Basudebpur', 'Orissa'),\r\n"
				+ "(962, 'Belpahar', 'Orissa'),\r\n"
				+ "(963, 'Bhadrak', 'Orissa'),\r\n"
				+ "(964, 'Bhawanipatna', 'Orissa'),\r\n"
				+ "(965, 'Bhuban', 'Orissa'),\r\n"
				+ "(966, 'Bhubaneswar', 'Orissa'),\r\n"
				+ "(967, 'Biramitrapur', 'Orissa'),\r\n"
				+ "(968, 'Brahmapur', 'Orissa'),\r\n"
				+ "(969, 'Brajrajnagar', 'Orissa'),\r\n"
				+ "(970, 'Byasanagar', 'Orissa'),\r\n"
				+ "(971, 'Cuttack', 'Orissa'),\r\n"
				+ "(972, 'Debagarh', 'Orissa'),\r\n"
				+ "(973, 'Dhenkanal', 'Orissa'),\r\n"
				+ "(974, 'Gunupur', 'Orissa'),\r\n"
				+ "(975, 'Hinjilicut', 'Orissa'),\r\n"
				+ "(976, 'Jagatsinghapur', 'Orissa'),\r\n"
				+ "(977, 'Jajapur', 'Orissa'),\r\n"
				+ "(978, 'Jaleswar', 'Orissa'),\r\n"
				+ "(979, 'Jatani', 'Orissa'),\r\n"
				+ "(980, 'Jeypur', 'Orissa'),\r\n"
				+ "(981, 'Jharsuguda', 'Orissa'),\r\n"
				+ "(982, 'Joda', 'Orissa'),\r\n"
				+ "(983, 'Kantabanji', 'Orissa'),\r\n"
				+ "(984, 'Karanjia', 'Orissa'),\r\n"
				+ "(985, 'Kendrapara', 'Orissa'),\r\n"
				+ "(986, 'Kendujhar', 'Orissa'),\r\n"
				+ "(987, 'Khordha', 'Orissa'),\r\n"
				+ "(988, 'Koraput', 'Orissa'),\r\n"
				+ "(989, 'Malkangiri', 'Orissa'),\r\n"
				+ "(990, 'Nabarangapur', 'Orissa'),\r\n"
				+ "(991, 'Paradip', 'Orissa'),\r\n"
				+ "(992, 'Parlakhemundi', 'Orissa'),\r\n"
				+ "(993, 'Pattamundai', 'Orissa'),\r\n"
				+ "(994, 'Phulabani', 'Orissa'),\r\n"
				+ "(995, 'Puri', 'Orissa'),\r\n"
				+ "(996, 'Rairangpur', 'Orissa'),\r\n"
				+ "(997, 'Rajagangapur', 'Orissa'),\r\n"
				+ "(998, 'Raurkela', 'Orissa'),\r\n"
				+ "(999, 'Rayagada', 'Orissa'),\r\n"
				+ "(1000, 'Sambalpur', 'Orissa'),\r\n"
				+ "(1001, 'Soro', 'Orissa'),\r\n"
				+ "(1002, 'Sunabeda', 'Orissa'),\r\n"
				+ "(1003, 'Sundargarh', 'Orissa'),\r\n"
				+ "(1004, 'Talcher', 'Orissa'),\r\n"
				+ "(1005, 'Titlagarh', 'Orissa'),\r\n"
				+ "(1006, 'Umarkote', 'Orissa'),\r\n"
				+ "(1007, 'Karaikal', 'Pondicherry'),\r\n"
				+ "(1008, 'Mahe', 'Pondicherry'),\r\n"
				+ "(1009, 'Pondicherry', 'Pondicherry'),\r\n"
				+ "(1010, 'Yanam', 'Pondicherry'),\r\n"
				+ "(1011, 'Ahmedgarh', 'Punjab'),\r\n"
				+ "(1012, 'Amritsar', 'Punjab'),\r\n"
				+ "(1013, 'Barnala', 'Punjab'),\r\n"
				+ "(1014, 'Batala', 'Punjab'),\r\n"
				+ "(1015, 'Bathinda', 'Punjab'),\r\n"
				+ "(1016, 'Bhagha Purana', 'Punjab'),\r\n"
				+ "(1017, 'Budhlada', 'Punjab'),\r\n"
				+ "(1018, 'Chandigarh', 'Punjab'),\r\n"
				+ "(1019, 'Dasua', 'Punjab'),\r\n"
				+ "(1020, 'Dhuri', 'Punjab'),\r\n"
				+ "(1021, 'Dinanagar', 'Punjab'),\r\n"
				+ "(1022, 'Faridkot', 'Punjab'),\r\n"
				+ "(1023, 'Fazilka', 'Punjab'),\r\n"
				+ "(1024, 'Firozpur', 'Punjab'),\r\n"
				+ "(1025, 'Firozpur Cantt.', 'Punjab'),\r\n"
				+ "(1026, 'Giddarbaha', 'Punjab'),\r\n"
				+ "(1027, 'Gobindgarh', 'Punjab'),\r\n"
				+ "(1028, 'Gurdaspur', 'Punjab'),\r\n"
				+ "(1029, 'Hoshiarpur', 'Punjab'),\r\n"
				+ "(1030, 'Jagraon', 'Punjab'),\r\n"
				+ "(1031, 'Jaitu', 'Punjab'),\r\n"
				+ "(1032, 'Jalalabad', 'Punjab'),\r\n"
				+ "(1033, 'Jalandhar', 'Punjab'),\r\n"
				+ "(1034, 'Jalandhar Cantt.', 'Punjab'),\r\n"
				+ "(1035, 'Jandiala', 'Punjab'),\r\n"
				+ "(1036, 'Kapurthala', 'Punjab'),\r\n"
				+ "(1037, 'Karoran', 'Punjab'),\r\n"
				+ "(1038, 'Kartarpur', 'Punjab'),\r\n"
				+ "(1039, 'Khanna', 'Punjab'),\r\n"
				+ "(1040, 'Kharar', 'Punjab'),\r\n"
				+ "(1041, 'Kot Kapura', 'Punjab'),\r\n"
				+ "(1042, 'Kurali', 'Punjab'),\r\n"
				+ "(1043, 'Longowal', 'Punjab'),\r\n"
				+ "(1044, 'Ludhiana', 'Punjab'),\r\n"
				+ "(1045, 'Malerkotla', 'Punjab'),\r\n"
				+ "(1046, 'Malout', 'Punjab'),\r\n"
				+ "(1047, 'Mansa', 'Punjab'),\r\n"
				+ "(1048, 'Maur', 'Punjab'),\r\n"
				+ "(1049, 'Moga', 'Punjab'),\r\n"
				+ "(1050, 'Mohali', 'Punjab'),\r\n"
				+ "(1051, 'Morinda', 'Punjab'),\r\n"
				+ "(1052, 'Mukerian', 'Punjab'),\r\n"
				+ "(1053, 'Muktsar', 'Punjab'),\r\n"
				+ "(1054, 'Nabha', 'Punjab'),\r\n"
				+ "(1055, 'Nakodar', 'Punjab'),\r\n"
				+ "(1056, 'Nangal', 'Punjab'),\r\n"
				+ "(1057, 'Nawanshahr', 'Punjab'),\r\n"
				+ "(1058, 'Pathankot', 'Punjab'),\r\n"
				+ "(1059, 'Patiala', 'Punjab'),\r\n"
				+ "(1060, 'Patran', 'Punjab'),\r\n"
				+ "(1061, 'Patti', 'Punjab'),\r\n"
				+ "(1062, 'Phagwara', 'Punjab'),\r\n"
				+ "(1063, 'Phillaur', 'Punjab'),\r\n"
				+ "(1064, 'Qadian', 'Punjab'),\r\n"
				+ "(1065, 'Raikot', 'Punjab'),\r\n"
				+ "(1066, 'Rajpura', 'Punjab'),\r\n"
				+ "(1067, 'Rampura Phul', 'Punjab'),\r\n"
				+ "(1068, 'Rupnagar', 'Punjab'),\r\n"
				+ "(1069, 'Samana', 'Punjab'),\r\n"
				+ "(1070, 'Sangrur', 'Punjab'),\r\n"
				+ "(1071, 'Sirhind Fatehgarh Sahib', 'Punjab'),\r\n"
				+ "(1072, 'Sujanpur', 'Punjab'),\r\n"
				+ "(1073, 'Sunam', 'Punjab'),\r\n"
				+ "(1074, 'Talwara', 'Punjab'),\r\n"
				+ "(1075, 'Tarn Taran', 'Punjab'),\r\n"
				+ "(1076, 'Urmar Tanda', 'Punjab'),\r\n"
				+ "(1077, 'Zira', 'Punjab'),\r\n"
				+ "(1078, 'Zirakpur', 'Punjab'),\r\n"
				+ "(1079, 'Bali', 'Rajastan'),\r\n"
				+ "(1080, 'Banswara', 'Rajastan'),\r\n"
				+ "(1081, 'Ajmer', 'Rajasthan'),\r\n"
				+ "(1082, 'Alwar', 'Rajasthan'),\r\n"
				+ "(1083, 'Bandikui', 'Rajasthan'),\r\n"
				+ "(1084, 'Baran', 'Rajasthan'),\r\n"
				+ "(1085, 'Barmer', 'Rajasthan'),\r\n"
				+ "(1086, 'Bikaner', 'Rajasthan'),\r\n"
				+ "(1087, 'Fatehpur', 'Rajasthan'),\r\n"
				+ "(1088, 'Jaipur', 'Rajasthan'),\r\n"
				+ "(1089, 'Jaisalmer', 'Rajasthan'),\r\n"
				+ "(1090, 'Jodhpur', 'Rajasthan'),\r\n"
				+ "(1091, 'Kota', 'Rajasthan'),\r\n"
				+ "(1092, 'Lachhmangarh', 'Rajasthan'),\r\n"
				+ "(1093, 'Ladnu', 'Rajasthan'),\r\n"
				+ "(1094, 'Lakheri', 'Rajasthan'),\r\n"
				+ "(1095, 'Lalsot', 'Rajasthan'),\r\n"
				+ "(1096, 'Losal', 'Rajasthan'),\r\n"
				+ "(1097, 'Makrana', 'Rajasthan'),\r\n"
				+ "(1098, 'Malpura', 'Rajasthan'),\r\n"
				+ "(1099, 'Mandalgarh', 'Rajasthan'),\r\n"
				+ "(1100, 'Mandawa', 'Rajasthan'),\r\n"
				+ "(1101, 'Mangrol', 'Rajasthan'),\r\n"
				+ "(1102, 'Merta City', 'Rajasthan'),\r\n"
				+ "(1103, 'Mount Abu', 'Rajasthan'),\r\n"
				+ "(1104, 'Nadbai', 'Rajasthan'),\r\n"
				+ "(1105, 'Nagar', 'Rajasthan'),\r\n"
				+ "(1106, 'Nagaur', 'Rajasthan'),\r\n"
				+ "(1107, 'Nargund', 'Rajasthan'),\r\n"
				+ "(1108, 'Nasirabad', 'Rajasthan'),\r\n"
				+ "(1109, 'Nathdwara', 'Rajasthan'),\r\n"
				+ "(1110, 'Navalgund', 'Rajasthan'),\r\n"
				+ "(1111, 'Nawalgarh', 'Rajasthan'),\r\n"
				+ "(1112, 'Neem-Ka-Thana', 'Rajasthan'),\r\n"
				+ "(1113, 'Nelamangala', 'Rajasthan'),\r\n"
				+ "(1114, 'Nimbahera', 'Rajasthan'),\r\n"
				+ "(1115, 'Nipani', 'Rajasthan'),\r\n"
				+ "(1116, 'Niwai', 'Rajasthan'),\r\n"
				+ "(1117, 'Nohar', 'Rajasthan'),\r\n"
				+ "(1118, 'Nokha', 'Rajasthan'),\r\n"
				+ "(1119, 'Pali', 'Rajasthan'),\r\n"
				+ "(1120, 'Phalodi', 'Rajasthan'),\r\n"
				+ "(1121, 'Phulera', 'Rajasthan'),\r\n"
				+ "(1122, 'Pilani', 'Rajasthan'),\r\n"
				+ "(1123, 'Pilibanga', 'Rajasthan'),\r\n"
				+ "(1124, 'Pindwara', 'Rajasthan'),\r\n"
				+ "(1125, 'Pipar City', 'Rajasthan'),\r\n"
				+ "(1126, 'Prantij', 'Rajasthan'),\r\n"
				+ "(1127, 'Pratapgarh', 'Rajasthan'),\r\n"
				+ "(1128, 'Raisinghnagar', 'Rajasthan'),\r\n"
				+ "(1129, 'Rajakhera', 'Rajasthan'),\r\n"
				+ "(1130, 'Rajaldesar', 'Rajasthan'),\r\n"
				+ "(1131, 'Rajgarh (Alwar)', 'Rajasthan'),\r\n"
				+ "(1132, 'Rajgarh (Churu', 'Rajasthan'),\r\n"
				+ "(1133, 'Rajsamand', 'Rajasthan'),\r\n"
				+ "(1134, 'Ramganj Mandi', 'Rajasthan'),\r\n"
				+ "(1135, 'Ramngarh', 'Rajasthan'),\r\n"
				+ "(1136, 'Ratangarh', 'Rajasthan'),\r\n"
				+ "(1137, 'Rawatbhata', 'Rajasthan'),\r\n"
				+ "(1138, 'Rawatsar', 'Rajasthan'),\r\n"
				+ "(1139, 'Reengus', 'Rajasthan'),\r\n"
				+ "(1140, 'Sadri', 'Rajasthan'),\r\n"
				+ "(1141, 'Sadulshahar', 'Rajasthan'),\r\n"
				+ "(1142, 'Sagwara', 'Rajasthan'),\r\n"
				+ "(1143, 'Sambhar', 'Rajasthan'),\r\n"
				+ "(1144, 'Sanchore', 'Rajasthan'),\r\n"
				+ "(1145, 'Sangaria', 'Rajasthan'),\r\n"
				+ "(1146, 'Sardarshahar', 'Rajasthan'),\r\n"
				+ "(1147, 'Sawai Madhopur', 'Rajasthan'),\r\n"
				+ "(1148, 'Shahpura', 'Rajasthan'),\r\n"
				+ "(1149, 'Shahpura', 'Rajasthan'),\r\n"
				+ "(1150, 'Sheoganj', 'Rajasthan'),\r\n"
				+ "(1151, 'Sikar', 'Rajasthan'),\r\n"
				+ "(1152, 'Sirohi', 'Rajasthan'),\r\n"
				+ "(1153, 'Sojat', 'Rajasthan'),\r\n"
				+ "(1154, 'Sri Madhopur', 'Rajasthan'),\r\n"
				+ "(1155, 'Sujangarh', 'Rajasthan'),\r\n"
				+ "(1156, 'Sumerpur', 'Rajasthan'),\r\n"
				+ "(1157, 'Suratgarh', 'Rajasthan'),\r\n"
				+ "(1158, 'Taranagar', 'Rajasthan'),\r\n"
				+ "(1159, 'Todabhim', 'Rajasthan'),\r\n"
				+ "(1160, 'Todaraisingh', 'Rajasthan'),\r\n"
				+ "(1161, 'Tonk', 'Rajasthan'),\r\n"
				+ "(1162, 'Udaipur', 'Rajasthan'),\r\n"
				+ "(1163, 'Udaipurwati', 'Rajasthan'),\r\n"
				+ "(1164, 'Vijainagar', 'Rajasthan'),\r\n"
				+ "(1165, 'Gangtok', 'Sikkim'),\r\n"
				+ "(1166, 'Calcutta', 'West Bengal'),\r\n"
				+ "(1167, 'Arakkonam', 'Tamil Nadu'),\r\n"
				+ "(1168, 'Arcot', 'Tamil Nadu'),\r\n"
				+ "(1169, 'Aruppukkottai', 'Tamil Nadu'),\r\n"
				+ "(1170, 'Bhavani', 'Tamil Nadu'),\r\n"
				+ "(1171, 'Chengalpattu', 'Tamil Nadu'),\r\n"
				+ "(1172, 'Chennai', 'Tamil Nadu'),\r\n"
				+ "(1173, 'Chinna salem', 'Tamil nadu'),\r\n"
				+ "(1174, 'Coimbatore', 'Tamil Nadu'),\r\n"
				+ "(1175, 'Coonoor', 'Tamil Nadu'),\r\n"
				+ "(1176, 'Cuddalore', 'Tamil Nadu'),\r\n"
				+ "(1177, 'Dharmapuri', 'Tamil Nadu'),\r\n"
				+ "(1178, 'Dindigul', 'Tamil Nadu'),\r\n"
				+ "(1179, 'Erode', 'Tamil Nadu'),\r\n"
				+ "(1180, 'Gudalur', 'Tamil Nadu'),\r\n"
				+ "(1181, 'Gudalur', 'Tamil Nadu'),\r\n"
				+ "(1182, 'Gudalur', 'Tamil Nadu'),\r\n"
				+ "(1183, 'Kanchipuram', 'Tamil Nadu'),\r\n"
				+ "(1184, 'Karaikudi', 'Tamil Nadu'),\r\n"
				+ "(1185, 'Karungal', 'Tamil Nadu'),\r\n"
				+ "(1186, 'Karur', 'Tamil Nadu'),\r\n"
				+ "(1187, 'Kollankodu', 'Tamil Nadu'),\r\n"
				+ "(1188, 'Lalgudi', 'Tamil Nadu'),\r\n"
				+ "(1189, 'Madurai', 'Tamil Nadu'),\r\n"
				+ "(1190, 'Nagapattinam', 'Tamil Nadu'),\r\n"
				+ "(1191, 'Nagercoil', 'Tamil Nadu'),\r\n"
				+ "(1192, 'Namagiripettai', 'Tamil Nadu'),\r\n"
				+ "(1193, 'Namakkal', 'Tamil Nadu'),\r\n"
				+ "(1194, 'Nandivaram-Guduvancheri', 'Tamil Nadu'),\r\n"
				+ "(1195, 'Nanjikottai', 'Tamil Nadu'),\r\n"
				+ "(1196, 'Natham', 'Tamil Nadu'),\r\n"
				+ "(1197, 'Nellikuppam', 'Tamil Nadu'),\r\n"
				+ "(1198, 'Neyveli', 'Tamil Nadu'),\r\n"
				+ "(1199, 'O'' Valley', 'Tamil Nadu'),\r\n"
				+ "(1200, 'Oddanchatram', 'Tamil Nadu'),\r\n"
				+ "(1201, 'P.N.Patti', 'Tamil Nadu'),\r\n"
				+ "(1202, 'Pacode', 'Tamil Nadu'),\r\n"
				+ "(1203, 'Padmanabhapuram', 'Tamil Nadu'),\r\n"
				+ "(1204, 'Palani', 'Tamil Nadu'),\r\n"
				+ "(1205, 'Palladam', 'Tamil Nadu'),\r\n"
				+ "(1206, 'Pallapatti', 'Tamil Nadu'),\r\n"
				+ "(1207, 'Pallikonda', 'Tamil Nadu'),\r\n"
				+ "(1208, 'Panagudi', 'Tamil Nadu'),\r\n"
				+ "(1209, 'Panruti', 'Tamil Nadu'),\r\n"
				+ "(1210, 'Paramakudi', 'Tamil Nadu'),\r\n"
				+ "(1211, 'Parangipettai', 'Tamil Nadu'),\r\n"
				+ "(1212, 'Pattukkottai', 'Tamil Nadu'),\r\n"
				+ "(1213, 'Perambalur', 'Tamil Nadu'),\r\n"
				+ "(1214, 'Peravurani', 'Tamil Nadu'),\r\n"
				+ "(1215, 'Periyakulam', 'Tamil Nadu'),\r\n"
				+ "(1216, 'Periyasemur', 'Tamil Nadu'),\r\n"
				+ "(1217, 'Pernampattu', 'Tamil Nadu'),\r\n"
				+ "(1218, 'Pollachi', 'Tamil Nadu'),\r\n"
				+ "(1219, 'Polur', 'Tamil Nadu'),\r\n"
				+ "(1220, 'Ponneri', 'Tamil Nadu'),\r\n"
				+ "(1221, 'Pudukkottai', 'Tamil Nadu'),\r\n"
				+ "(1222, 'Pudupattinam', 'Tamil Nadu'),\r\n"
				+ "(1223, 'Puliyankudi', 'Tamil Nadu'),\r\n"
				+ "(1224, 'Punjaipugalur', 'Tamil Nadu'),\r\n"
				+ "(1225, 'Rajapalayam', 'Tamil Nadu'),\r\n"
				+ "(1226, 'Ramanathapuram', 'Tamil Nadu'),\r\n"
				+ "(1227, 'Rameshwaram', 'Tamil Nadu'),\r\n"
				+ "(1228, 'Rasipuram', 'Tamil Nadu'),\r\n"
				+ "(1229, 'Salem', 'Tamil Nadu'),\r\n"
				+ "(1230, 'Sankarankoil', 'Tamil Nadu'),\r\n"
				+ "(1231, 'Sankari', 'Tamil Nadu'),\r\n"
				+ "(1232, 'Sathyamangalam', 'Tamil Nadu'),\r\n"
				+ "(1233, 'Sattur', 'Tamil Nadu'),\r\n"
				+ "(1234, 'Shenkottai', 'Tamil Nadu'),\r\n"
				+ "(1235, 'Sholavandan', 'Tamil Nadu'),\r\n"
				+ "(1236, 'Sholingur', 'Tamil Nadu'),\r\n"
				+ "(1237, 'Sirkali', 'Tamil Nadu'),\r\n"
				+ "(1238, 'Sivaganga', 'Tamil Nadu'),\r\n"
				+ "(1239, 'Sivagiri', 'Tamil Nadu'),\r\n"
				+ "(1240, 'Sivakasi', 'Tamil Nadu'),\r\n"
				+ "(1241, 'Srivilliputhur', 'Tamil Nadu'),\r\n"
				+ "(1242, 'Surandai', 'Tamil Nadu'),\r\n"
				+ "(1243, 'Suriyampalayam', 'Tamil Nadu'),\r\n"
				+ "(1244, 'Tenkasi', 'Tamil Nadu'),\r\n"
				+ "(1245, 'Thammampatti', 'Tamil Nadu'),\r\n"
				+ "(1246, 'Thanjavur', 'Tamil Nadu'),\r\n"
				+ "(1247, 'Tharamangalam', 'Tamil Nadu'),\r\n"
				+ "(1248, 'Tharangambadi', 'Tamil Nadu'),\r\n"
				+ "(1249, 'Theni Allinagaram', 'Tamil Nadu'),\r\n"
				+ "(1250, 'Thirumangalam', 'Tamil Nadu'),\r\n"
				+ "(1251, 'Thirunindravur', 'Tamil Nadu'),\r\n"
				+ "(1252, 'Thiruparappu', 'Tamil Nadu'),\r\n"
				+ "(1253, 'Thirupuvanam', 'Tamil Nadu'),\r\n"
				+ "(1254, 'Thiruthuraipoondi', 'Tamil Nadu'),\r\n"
				+ "(1255, 'Thiruvallur', 'Tamil Nadu'),\r\n"
				+ "(1256, 'Thiruvarur', 'Tamil Nadu'),\r\n"
				+ "(1257, 'Thoothukudi', 'Tamil Nadu'),\r\n"
				+ "(1258, 'Thuraiyur', 'Tamil Nadu'),\r\n"
				+ "(1259, 'Tindivanam', 'Tamil Nadu'),\r\n"
				+ "(1260, 'Tiruchendur', 'Tamil Nadu'),\r\n"
				+ "(1261, 'Tiruchengode', 'Tamil Nadu'),\r\n"
				+ "(1262, 'Tiruchirappalli', 'Tamil Nadu'),\r\n"
				+ "(1263, 'Tirukalukundram', 'Tamil Nadu'),\r\n"
				+ "(1264, 'Tirukkoyilur', 'Tamil Nadu'),\r\n"
				+ "(1265, 'Tirunelveli', 'Tamil Nadu'),\r\n"
				+ "(1266, 'Tirupathur', 'Tamil Nadu'),\r\n"
				+ "(1267, 'Tirupathur', 'Tamil Nadu'),\r\n"
				+ "(1268, 'Tiruppur', 'Tamil Nadu'),\r\n"
				+ "(1269, 'Tiruttani', 'Tamil Nadu'),\r\n"
				+ "(1270, 'Tiruvannamalai', 'Tamil Nadu'),\r\n"
				+ "(1271, 'Tiruvethipuram', 'Tamil Nadu'),\r\n"
				+ "(1272, 'Tittakudi', 'Tamil Nadu'),\r\n"
				+ "(1273, 'Udhagamandalam', 'Tamil Nadu'),\r\n"
				+ "(1274, 'Udumalaipettai', 'Tamil Nadu'),\r\n"
				+ "(1275, 'Unnamalaikadai', 'Tamil Nadu'),\r\n"
				+ "(1276, 'Usilampatti', 'Tamil Nadu'),\r\n"
				+ "(1277, 'Uthamapalayam', 'Tamil Nadu'),\r\n"
				+ "(1278, 'Uthiramerur', 'Tamil Nadu'),\r\n"
				+ "(1279, 'Vadakkuvalliyur', 'Tamil Nadu'),\r\n"
				+ "(1280, 'Vadalur', 'Tamil Nadu'),\r\n"
				+ "(1281, 'Vadipatti', 'Tamil Nadu'),\r\n"
				+ "(1282, 'Valparai', 'Tamil Nadu'),\r\n"
				+ "(1283, 'Vandavasi', 'Tamil Nadu'),\r\n"
				+ "(1284, 'Vaniyambadi', 'Tamil Nadu'),\r\n"
				+ "(1285, 'Vedaranyam', 'Tamil Nadu'),\r\n"
				+ "(1286, 'Vellakoil', 'Tamil Nadu'),\r\n"
				+ "(1287, 'Vellore', 'Tamil Nadu'),\r\n"
				+ "(1288, 'Vikramasingapuram', 'Tamil Nadu'),\r\n"
				+ "(1289, 'Viluppuram', 'Tamil Nadu'),\r\n"
				+ "(1290, 'Virudhachalam', 'Tamil Nadu'),\r\n"
				+ "(1291, 'Virudhunagar', 'Tamil Nadu'),\r\n"
				+ "(1292, 'Viswanatham', 'Tamil Nadu'),\r\n"
				+ "(1293, 'Agartala', 'Tripura'),\r\n"
				+ "(1294, 'Badharghat', 'Tripura'),\r\n"
				+ "(1295, 'Dharmanagar', 'Tripura'),\r\n"
				+ "(1296, 'Indranagar', 'Tripura'),\r\n"
				+ "(1297, 'Jogendranagar', 'Tripura'),\r\n"
				+ "(1298, 'Kailasahar', 'Tripura'),\r\n"
				+ "(1299, 'Khowai', 'Tripura'),\r\n"
				+ "(1300, 'Pratapgarh', 'Tripura'),\r\n"
				+ "(1301, 'Udaipur', 'Tripura'),\r\n"
				+ "(1302, 'Achhnera', 'Uttar Pradesh'),\r\n"
				+ "(1303, 'Adari', 'Uttar Pradesh'),\r\n"
				+ "(1304, 'Agra', 'Uttar Pradesh'),\r\n"
				+ "(1305, 'Aligarh', 'Uttar Pradesh'),\r\n"
				+ "(1306, 'Allahabad', 'Uttar Pradesh'),\r\n"
				+ "(1307, 'Amroha', 'Uttar Pradesh'),\r\n"
				+ "(1308, 'Azamgarh', 'Uttar Pradesh'),\r\n"
				+ "(1309, 'Bahraich', 'Uttar Pradesh'),\r\n"
				+ "(1310, 'Ballia', 'Uttar Pradesh'),\r\n"
				+ "(1311, 'Balrampur', 'Uttar Pradesh'),\r\n"
				+ "(1312, 'Banda', 'Uttar Pradesh'),\r\n"
				+ "(1313, 'Bareilly', 'Uttar Pradesh'),\r\n"
				+ "(1314, 'Chandausi', 'Uttar Pradesh'),\r\n"
				+ "(1315, 'Dadri', 'Uttar Pradesh'),\r\n"
				+ "(1316, 'Deoria', 'Uttar Pradesh'),\r\n"
				+ "(1317, 'Etawah', 'Uttar Pradesh'),\r\n"
				+ "(1318, 'Fatehabad', 'Uttar Pradesh'),\r\n"
				+ "(1319, 'Fatehpur', 'Uttar Pradesh'),\r\n"
				+ "(1320, 'Fatehpur', 'Uttar Pradesh'),\r\n"
				+ "(1321, 'Greater Noida', 'Uttar Pradesh'),\r\n"
				+ "(1322, 'Hamirpur', 'Uttar Pradesh'),\r\n"
				+ "(1323, 'Hardoi', 'Uttar Pradesh'),\r\n"
				+ "(1324, 'Jajmau', 'Uttar Pradesh'),\r\n"
				+ "(1325, 'Jaunpur', 'Uttar Pradesh'),\r\n"
				+ "(1326, 'Jhansi', 'Uttar Pradesh'),\r\n"
				+ "(1327, 'Kalpi', 'Uttar Pradesh'),\r\n"
				+ "(1328, 'Kanpur', 'Uttar Pradesh'),\r\n"
				+ "(1329, 'Kota', 'Uttar Pradesh'),\r\n"
				+ "(1330, 'Laharpur', 'Uttar Pradesh'),\r\n"
				+ "(1331, 'Lakhimpur', 'Uttar Pradesh'),\r\n"
				+ "(1332, 'Lal Gopalganj Nindaura', 'Uttar Pradesh'),\r\n"
				+ "(1333, 'Lalganj', 'Uttar Pradesh'),\r\n"
				+ "(1334, 'Lalitpur', 'Uttar Pradesh'),\r\n"
				+ "(1335, 'Lar', 'Uttar Pradesh'),\r\n"
				+ "(1336, 'Loni', 'Uttar Pradesh'),\r\n"
				+ "(1337, 'Lucknow', 'Uttar Pradesh'),\r\n"
				+ "(1338, 'Mathura', 'Uttar Pradesh'),\r\n"
				+ "(1339, 'Meerut', 'Uttar Pradesh'),\r\n"
				+ "(1340, 'Modinagar', 'Uttar Pradesh'),\r\n"
				+ "(1341, 'Muradnagar', 'Uttar Pradesh'),\r\n"
				+ "(1342, 'Nagina', 'Uttar Pradesh'),\r\n"
				+ "(1343, 'Najibabad', 'Uttar Pradesh'),\r\n"
				+ "(1344, 'Nakur', 'Uttar Pradesh'),\r\n"
				+ "(1345, 'Nanpara', 'Uttar Pradesh'),\r\n"
				+ "(1346, 'Naraura', 'Uttar Pradesh'),\r\n"
				+ "(1347, 'Naugawan Sadat', 'Uttar Pradesh'),\r\n"
				+ "(1348, 'Nautanwa', 'Uttar Pradesh'),\r\n"
				+ "(1349, 'Nawabganj', 'Uttar Pradesh'),\r\n"
				+ "(1350, 'Nehtaur', 'Uttar Pradesh'),\r\n"
				+ "(1351, 'NOIDA', 'Uttar Pradesh'),\r\n"
				+ "(1352, 'Noorpur', 'Uttar Pradesh'),\r\n"
				+ "(1353, 'Obra', 'Uttar Pradesh'),\r\n"
				+ "(1354, 'Orai', 'Uttar Pradesh'),\r\n"
				+ "(1355, 'Padrauna', 'Uttar Pradesh'),\r\n"
				+ "(1356, 'Palia Kalan', 'Uttar Pradesh'),\r\n"
				+ "(1357, 'Parasi', 'Uttar Pradesh'),\r\n"
				+ "(1358, 'Phulpur', 'Uttar Pradesh'),\r\n"
				+ "(1359, 'Pihani', 'Uttar Pradesh'),\r\n"
				+ "(1360, 'Pilibhit', 'Uttar Pradesh'),\r\n"
				+ "(1361, 'Pilkhuwa', 'Uttar Pradesh'),\r\n"
				+ "(1362, 'Powayan', 'Uttar Pradesh'),\r\n"
				+ "(1363, 'Pukhrayan', 'Uttar Pradesh'),\r\n"
				+ "(1364, 'Puranpur', 'Uttar Pradesh'),\r\n"
				+ "(1365, 'Purquazi', 'Uttar Pradesh'),\r\n"
				+ "(1366, 'Purwa', 'Uttar Pradesh'),\r\n"
				+ "(1367, 'Rae Bareli', 'Uttar Pradesh'),\r\n"
				+ "(1368, 'Rampur', 'Uttar Pradesh'),\r\n"
				+ "(1369, 'Rampur Maniharan', 'Uttar Pradesh'),\r\n"
				+ "(1370, 'Rasra', 'Uttar Pradesh'),\r\n"
				+ "(1371, 'Rath', 'Uttar Pradesh'),\r\n"
				+ "(1372, 'Renukoot', 'Uttar Pradesh'),\r\n"
				+ "(1373, 'Reoti', 'Uttar Pradesh'),\r\n"
				+ "(1374, 'Robertsganj', 'Uttar Pradesh'),\r\n"
				+ "(1375, 'Rudauli', 'Uttar Pradesh'),\r\n"
				+ "(1376, 'Rudrapur', 'Uttar Pradesh'),\r\n"
				+ "(1377, 'Sadabad', 'Uttar Pradesh'),\r\n"
				+ "(1378, 'Safipur', 'Uttar Pradesh'),\r\n"
				+ "(1379, 'Saharanpur', 'Uttar Pradesh'),\r\n"
				+ "(1380, 'Sahaspur', 'Uttar Pradesh'),\r\n"
				+ "(1381, 'Sahaswan', 'Uttar Pradesh'),\r\n"
				+ "(1382, 'Sahawar', 'Uttar Pradesh'),\r\n"
				+ "(1383, 'Sahjanwa', 'Uttar Pradesh'),\r\n"
				+ "(1384, '\"Saidpur', ' Ghazipur\"'),\r\n"
				+ "(1385, 'Sambhal', 'Uttar Pradesh'),\r\n"
				+ "(1386, 'Samdhan', 'Uttar Pradesh'),\r\n"
				+ "(1387, 'Samthar', 'Uttar Pradesh'),\r\n"
				+ "(1388, 'Sandi', 'Uttar Pradesh'),\r\n"
				+ "(1389, 'Sandila', 'Uttar Pradesh'),\r\n"
				+ "(1390, 'Sardhana', 'Uttar Pradesh'),\r\n"
				+ "(1391, 'Seohara', 'Uttar Pradesh'),\r\n"
				+ "(1392, '\"Shahabad', ' Hardoi\"'),\r\n"
				+ "(1393, '\"Shahabad', ' Rampur\"'),\r\n"
				+ "(1394, 'Shahganj', 'Uttar Pradesh'),\r\n"
				+ "(1395, 'Shahjahanpur', 'Uttar Pradesh'),\r\n"
				+ "(1396, 'Shamli', 'Uttar Pradesh'),\r\n"
				+ "(1397, '\"Shamsabad', ' Agra\"'),\r\n"
				+ "(1398, '\"Shamsabad', ' Farrukhabad\"'),\r\n"
				+ "(1399, 'Sherkot', 'Uttar Pradesh'),\r\n"
				+ "(1400, '\"Shikarpur', ' Bulandshahr\"'),\r\n"
				+ "(1401, 'Shikohabad', 'Uttar Pradesh'),\r\n"
				+ "(1402, 'Shishgarh', 'Uttar Pradesh'),\r\n"
				+ "(1403, 'Siana', 'Uttar Pradesh'),\r\n"
				+ "(1404, 'Sikanderpur', 'Uttar Pradesh'),\r\n"
				+ "(1405, 'Sikandra Rao', 'Uttar Pradesh'),\r\n"
				+ "(1406, 'Sikandrabad', 'Uttar Pradesh'),\r\n"
				+ "(1407, 'Sirsaganj', 'Uttar Pradesh'),\r\n"
				+ "(1408, 'Sirsi', 'Uttar Pradesh'),\r\n"
				+ "(1409, 'Sitapur', 'Uttar Pradesh'),\r\n"
				+ "(1410, 'Soron', 'Uttar Pradesh'),\r\n"
				+ "(1411, 'Suar', 'Uttar Pradesh'),\r\n"
				+ "(1412, 'Sultanpur', 'Uttar Pradesh'),\r\n"
				+ "(1413, 'Sumerpur', 'Uttar Pradesh'),\r\n"
				+ "(1414, 'Tanda', 'Uttar Pradesh'),\r\n"
				+ "(1415, 'Tanda', 'Uttar Pradesh'),\r\n"
				+ "(1416, 'Tetri Bazar', 'Uttar Pradesh'),\r\n"
				+ "(1417, 'Thakurdwara', 'Uttar Pradesh'),\r\n"
				+ "(1418, 'Thana Bhawan', 'Uttar Pradesh'),\r\n"
				+ "(1419, 'Tilhar', 'Uttar Pradesh'),\r\n"
				+ "(1420, 'Tirwaganj', 'Uttar Pradesh'),\r\n"
				+ "(1421, 'Tulsipur', 'Uttar Pradesh'),\r\n"
				+ "(1422, 'Tundla', 'Uttar Pradesh'),\r\n"
				+ "(1423, 'Unnao', 'Uttar Pradesh'),\r\n"
				+ "(1424, 'Utraula', 'Uttar Pradesh'),\r\n"
				+ "(1425, 'Varanasi', 'Uttar Pradesh'),\r\n"
				+ "(1426, 'Vrindavan', 'Uttar Pradesh'),\r\n"
				+ "(1427, 'Warhapur', 'Uttar Pradesh'),\r\n"
				+ "(1428, 'Zaidpur', 'Uttar Pradesh'),\r\n"
				+ "(1429, 'Zamania', 'Uttar Pradesh'),\r\n"
				+ "(1430, 'Almora', 'Uttarakhand'),\r\n"
				+ "(1431, 'Bazpur', 'Uttarakhand'),\r\n"
				+ "(1432, 'Chamba', 'Uttarakhand'),\r\n"
				+ "(1433, 'Dehradun', 'Uttarakhand'),\r\n"
				+ "(1434, 'Haldwani', 'Uttarakhand'),\r\n"
				+ "(1435, 'Haridwar', 'Uttarakhand'),\r\n"
				+ "(1436, 'Jaspur', 'Uttarakhand'),\r\n"
				+ "(1437, 'Kashipur', 'Uttarakhand'),\r\n"
				+ "(1438, 'kichha', 'Uttarakhand'),\r\n"
				+ "(1439, 'Kotdwara', 'Uttarakhand'),\r\n"
				+ "(1440, 'Manglaur', 'Uttarakhand'),\r\n"
				+ "(1441, 'Mussoorie', 'Uttarakhand'),\r\n"
				+ "(1442, 'Nagla', 'Uttarakhand'),\r\n"
				+ "(1443, 'Nainital', 'Uttarakhand'),\r\n"
				+ "(1444, 'Pauri', 'Uttarakhand'),\r\n"
				+ "(1445, 'Pithoragarh', 'Uttarakhand'),\r\n"
				+ "(1446, 'Ramnagar', 'Uttarakhand'),\r\n"
				+ "(1447, 'Rishikesh', 'Uttarakhand'),\r\n"
				+ "(1448, 'Roorkee', 'Uttarakhand'),\r\n"
				+ "(1449, 'Rudrapur', 'Uttarakhand'),\r\n"
				+ "(1450, 'Sitarganj', 'Uttarakhand'),\r\n"
				+ "(1451, 'Tehri', 'Uttarakhand'),\r\n"
				+ "(1452, 'Muzaffarnagar', 'Uttarpradesh'),\r\n"
				+ "(1453, '\"Adra', ' Purulia\"'),\r\n"
				+ "(1454, 'Alipurduar', 'West Bengal'),\r\n"
				+ "(1455, 'Arambagh', 'West Bengal'),\r\n"
				+ "(1456, 'Asansol', 'West Bengal'),\r\n"
				+ "(1457, 'Baharampur', 'West Bengal'),\r\n"
				+ "(1458, 'Bally', 'West Bengal'),\r\n"
				+ "(1459, 'Balurghat', 'West Bengal'),\r\n"
				+ "(1460, 'Bankura', 'West Bengal'),\r\n"
				+ "(1461, 'Barakar', 'West Bengal'),\r\n"
				+ "(1462, 'Barasat', 'West Bengal'),\r\n"
				+ "(1463, 'Bardhaman', 'West Bengal'),\r\n"
				+ "(1464, 'Bidhan Nagar', 'West Bengal'),\r\n"
				+ "(1465, 'Chinsura', 'West Bengal'),\r\n"
				+ "(1466, 'Contai', 'West Bengal'),\r\n"
				+ "(1467, 'Cooch Behar', 'West Bengal'),\r\n"
				+ "(1468, 'Darjeeling', 'West Bengal'),\r\n"
				+ "(1469, 'Durgapur', 'West Bengal'),\r\n"
				+ "(1470, 'Haldia', 'West Bengal'),\r\n"
				+ "(1471, 'Howrah', 'West Bengal'),\r\n"
				+ "(1472, 'Islampur', 'West Bengal'),\r\n"
				+ "(1473, 'Jhargram', 'West Bengal'),\r\n"
				+ "(1474, 'Kharagpur', 'West Bengal'),\r\n"
				+ "(1475, 'Kolkata', 'West Bengal'),\r\n"
				+ "(1476, 'Mainaguri', 'West Bengal'),\r\n"
				+ "(1477, 'Mal', 'West Bengal'),\r\n"
				+ "(1478, 'Mathabhanga', 'West Bengal'),\r\n"
				+ "(1479, 'Medinipur', 'West Bengal'),\r\n"
				+ "(1480, 'Memari', 'West Bengal'),\r\n"
				+ "(1481, 'Monoharpur', 'West Bengal'),\r\n"
				+ "(1482, 'Murshidabad', 'West Bengal'),\r\n"
				+ "(1483, 'Nabadwip', 'West Bengal'),\r\n"
				+ "(1484, 'Naihati', 'West Bengal'),\r\n"
				+ "(1485, 'Panchla', 'West Bengal'),\r\n"
				+ "(1486, 'Pandua', 'West Bengal'),\r\n"
				+ "(1487, 'Paschim Punropara', 'West Bengal'),\r\n"
				+ "(1488, 'Purulia', 'West Bengal'),\r\n"
				+ "(1489, 'Raghunathpur', 'West Bengal'),\r\n"
				+ "(1490, 'Raiganj', 'West Bengal'),\r\n"
				+ "(1491, 'Rampurhat', 'West Bengal'),\r\n"
				+ "(1492, 'Ranaghat', 'West Bengal'),\r\n"
				+ "(1493, 'Sainthia', 'West Bengal'),\r\n"
				+ "(1494, 'Santipur', 'West Bengal'),\r\n"
				+ "(1495, 'Siliguri', 'West Bengal'),\r\n"
				+ "(1496, 'Sonamukhi', 'West Bengal'),\r\n"
				+ "(1497, 'Srirampore', 'West Bengal'),\r\n"
				+ "(1498, 'Suri', 'West Bengal'),\r\n"
				+ "(1499, 'Taki', 'West Bengal'),\r\n"
				+ "(1500, 'Tamluk', 'West Bengal'),\r\n"
				+ "(1501, 'Tarakeswar', 'West Bengal'),\r\n"
				+ "(1502, 'Chikmagalur', 'Karnataka'),\r\n"
				+ "(1503, 'Davanagere', 'Karnataka'),\r\n"
				+ "(1504, 'Dharwad', 'Karnataka'),\r\n"
				+ "(1505, 'Gadag', 'Karnataka'),\r\n"
				+ "(1506, 'Chennai', 'Tamil Nadu'),\r\n"
				+ "(1507, 'Coimbatore', 'Tamil Nadu'),\r\n"
				+ "(1508, 'Barrackpur', 'unknown'),\r\n"
				+ "(1509, 'Barwani', 'unknown'),\r\n"
				+ "(1510, 'Basna', 'unknown'),\r\n"
				+ "(1511, 'Bawal', 'unknown'),\r\n"
				+ "(1512, 'Beawar', 'unknown'),\r\n"
				+ "(1513, 'Berhampur', 'unknown'),\r\n"
				+ "(1514, 'Bhajanpura', 'unknown'),\r\n"
				+ "(1515, 'Bhandara', 'unknown'),\r\n"
				+ "(1516, 'Bharatpur', 'unknown'),\r\n"
				+ "(1517, 'Bharthana', 'unknown'),\r\n"
				+ "(1518, 'Bhilai', 'unknown'),\r\n"
				+ "(1519, 'Bhilwara', 'unknown'),\r\n"
				+ "(1520, 'Bhinmal', 'unknown'),\r\n"
				+ "(1521, 'Bhiwandi', 'unknown'),\r\n"
				+ "(1522, 'Bhusawal', 'unknown'),\r\n"
				+ "(1523, 'Bidar', 'unknown'),\r\n"
				+ "(1524, 'Bijnaur', 'unknown'),\r\n"
				+ "(1525, 'Bilara', 'unknown'),\r\n"
				+ "(1527, 'Budaun', 'unknown'),\r\n"
				+ "(1528, 'Bulandshahr', 'unknown'),\r\n"
				+ "(1529, 'Burla', 'unknown'),\r\n"
				+ "(1532, 'Chakeri', 'unknown'),\r\n"
				+ "(1533, 'Champawat', 'unknown'),\r\n"
				+ "(1534, 'Chandil', 'unknown'),\r\n"
				+ "(1535, 'Chandrapur', 'unknown'),\r\n"
				+ "(1536, 'Chapirevula', 'unknown'),\r\n"
				+ "(1537, 'Charkhari', 'unknown'),\r\n"
				+ "(1538, 'Charkhi Dadri', 'unknown'),\r\n"
				+ "(1539, 'Chhindwara', 'unknown'),\r\n"
				+ "(1540, 'Chiplun', 'unknown'),\r\n"
				+ "(1541, 'Chitrakoot', 'unknown'),\r\n"
				+ "(1542, 'Churu', 'unknown'),\r\n"
				+ "(1543, 'Dalkhola', 'unknown'),\r\n"
				+ "(1544, 'Damoh', 'unknown'),\r\n"
				+ "(1545, 'Daund', 'unknown'),\r\n"
				+ "(1546, 'Dehgam', 'unknown'),\r\n"
				+ "(1547, 'Devgarh', 'unknown'),\r\n"
				+ "(1548, 'Dhulian', 'unknown'),\r\n"
				+ "(1549, 'Dumdum', 'unknown'),\r\n"
				+ "(1550, 'Dwarka1', 'unknown'),\r\n"
				+ "(1551, 'Etah', 'unknown'),\r\n"
				+ "(1552, 'Faizabad', 'unknown'),\r\n"
				+ "(1553, 'Falna', 'unknown'),\r\n"
				+ "(1554, 'Farrukhabad', 'unknown'),\r\n"
				+ "(1555, 'Fatehgarh', 'unknown'),\r\n"
				+ "(1556, 'Fatehpur Chaurasi', 'unknown'),\r\n"
				+ "(1557, 'Fatehpur Sikri', 'unknown'),\r\n"
				+ "(1558, 'Firozabad', 'unknown'),\r\n"
				+ "(1559, 'Gadchiroli', 'unknown'),\r\n"
				+ "(1560, 'Gandhidham', 'unknown'),\r\n"
				+ "(1561, 'Ganjam', 'unknown'),\r\n"
				+ "(1562, 'Ghatampur', 'unknown'),\r\n"
				+ "(1563, 'Ghatanji', 'unknown'),\r\n"
				+ "(1564, 'Ghaziabad', 'unknown'),\r\n"
				+ "(1565, 'Ghazipur', 'unknown'),\r\n"
				+ "(1566, 'Goa Velha', 'unknown'),\r\n"
				+ "(1567, 'Gokak', 'unknown'),\r\n"
				+ "(1568, 'Gondiya', 'unknown'),\r\n"
				+ "(1569, 'Gorakhpur', 'unknown'),\r\n"
				+ "(1571, 'Guna', 'unknown'),\r\n"
				+ "(1572, 'Hanumangarh', 'unknown'),\r\n"
				+ "(1573, 'Harda', 'unknown'),\r\n"
				+ "(1574, 'Harsawa', 'unknown'),\r\n"
				+ "(1575, 'Hastinapur', 'unknown'),\r\n"
				+ "(1576, 'Hathras', 'unknown'),\r\n"
				+ "(1579, 'Jagadhri', 'unknown'),\r\n"
				+ "(1580, 'Jais', 'unknown'),\r\n"
				+ "(1581, 'Jaitaran', 'unknown'),\r\n"
				+ "(1582, 'Jalgaon', 'unknown'),\r\n"
				+ "(1583, 'Jalore', 'unknown'),\r\n"
				+ "(1584, 'Jhabua', 'unknown'),\r\n"
				+ "(1585, 'Jhalawar', 'unknown'),\r\n"
				+ "(1586, 'Jhunjhunu', 'unknown'),\r\n"
				+ "(1588, 'Junnar', 'unknown'),\r\n"
				+ "(1589, 'Kailaras', 'unknown'),\r\n"
				+ "(1590, 'Kalburgi', 'unknown'),\r\n"
				+ "(1591, 'Kalimpong', 'unknown'),\r\n"
				+ "(1592, 'Kamthi', 'unknown'),\r\n"
				+ "(1593, 'Kanpur', 'unknown'),\r\n"
				+ "(1594, 'Karad', 'unknown'),\r\n"
				+ "(1595, 'Keylong', 'unknown'),\r\n"
				+ "(1596, 'Kheri', 'unknown'),\r\n"
				+ "(1598, 'Khurai', 'unknown'),\r\n"
				+ "(1600, 'Kodad', 'unknown'),\r\n"
				+ "(1601, 'Konnagar', 'unknown'),\r\n"
				+ "(1602, 'Krishnanagar', 'unknown'),\r\n"
				+ "(1603, 'Kuchinda', 'unknown'),\r\n"
				+ "(1605, 'Madhyamgram', 'unknown'),\r\n"
				+ "(1606, 'Mahabaleswar', 'unknown'),\r\n"
				+ "(1608, 'Mahoba', 'unknown'),\r\n"
				+ "(1609, 'Mahwa', 'unknown'),\r\n"
				+ "(1614, 'Manesar', 'unknown'),\r\n"
				+ "(1615, 'Mangalagiri', 'unknown'),\r\n"
				+ "(1616, 'Mira-Bhayandar', 'unknown'),\r\n"
				+ "(1617, 'Mirzapur', 'unknown'),\r\n"
				+ "(1618, 'Mithapur', 'unknown'),\r\n"
				+ "(1619, 'Mohania', 'unknown'),\r\n"
				+ "(1620, 'Mokama', 'unknown'),\r\n"
				+ "(1621, 'Moradabad', 'unknown'),\r\n"
				+ "(1622, 'Mukatsar', 'unknown'),\r\n"
				+ "(1623, 'Nagalapuram', 'unknown');";
		stmt = con.createStatement();
		stmt.execute(createColursTable);
		System.out.println("Table CONTACTS_APP_COLOURS created successfully");
	} catch (Exception e) {
		System.out.println("Failed to create table");
		e.printStackTrace();
	}
}
}
